import type { WidgetConfig } from '../../common/wigmix-core';
import type { LanguagePack } from '../../common/locales/locale';

export const DEFAULT_TEXTS: LanguagePack = {
  en: {
    widgetTitle: 'Shopping Assistant',
    openingMessage1: 'Let\'s get started',
    openingMessage2: 'Tell us about what your styling needs and we will help you find the perfect item for you',
    chatBoxPlaceholder: 'Type your message',
    triggerCTA: 'Style Assistant',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} off',
    addToCart: 'Add to Cart',
    a11yStartNewChat: 'Start new chat',
    a11yCloseShoppingAssistant: 'Close shopping assistant',
    a11yCloseCamera: 'Close camera',
    a11yTakePhoto: 'Take photo',
    a11ySwitchCamera: 'Switch camera',
    a11yOpenCamera: 'Open camera',
    a11yUploadImage: 'Upload image',
    a11ySendMessage: 'Send message',
    a11yScrollToLatestMessage: 'Scroll to latest message',
    a11yCameraDrawer: 'Camera',
    a11yChatInput: 'Type your message to the shopping assistant',
    a11yUploadedImage: 'Uploaded image',
    a11yAssistantThinking: 'Assistant is thinking',
    a11yProductResultsShown: 'Product results shown: {count}',
    a11yChatMessages: 'Shopping assistant messages',
    a11yCameraPreview: 'Camera preview — point at the item to search',
    a11ySuggestedReplies: 'Suggested replies',
    a11yViewProduct: 'View product',
    a11yStartVoiceInput: 'Start voice input',
    a11yStopVoiceInput: 'Stop recording and send',
    a11yTranscribingVoice: 'Transcribing voice message',
    a11yEnableVoiceReading: 'Enable voice reading',
    a11yDisableVoiceReading: 'Disable voice reading',
    voiceInputError: 'Voice input unavailable',
    showMore: 'Show more...',
    nowDescribing: 'Now Describing',
    holdMicToRecord: 'Hold the mic to record',
    a11yAddImage: 'Add image',
    a11yListening: 'Listening',
    a11yHoldMicInstructions: 'Press and hold, or press and hold Space or Enter, to record. Release to send.',
    a11yCameraError: 'Camera unavailable — check permissions or try switching cameras',
    a11yMinimizeShoppingAssistant: 'Minimize shopping assistant',
  },
  es: {
    widgetTitle: 'Asistente de estilo',
    openingMessage1: 'Empecemos',
    openingMessage2: 'Cuéntanos sobre tus necesidades de estilo y te ayudaremos a encontrar el artículo perfecto para ti',
    chatBoxPlaceholder: 'Escribe tu mensaje',
    triggerCTA: 'Asistente de estilo',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de descuento',
    addToCart: 'Agregar al carrito',
    a11yStartNewChat: 'Iniciar nuevo chat',
    a11yCloseShoppingAssistant: 'Cerrar asistente de compras',
    a11yCloseCamera: 'Cerrar cámara',
    a11yTakePhoto: 'Tomar foto',
    a11ySwitchCamera: 'Cambiar cámara',
    a11yOpenCamera: 'Abrir cámara',
    a11yUploadImage: 'Subir imagen',
    a11ySendMessage: 'Enviar mensaje',
    a11yScrollToLatestMessage: 'Ir al mensaje más reciente',
    a11yCameraDrawer: 'Cámara',
    a11yChatInput: 'Escribe tu mensaje al asistente de compras',
    a11yUploadedImage: 'Imagen subida',
    a11yAssistantThinking: 'El asistente está pensando',
    a11yProductResultsShown: 'Resultados de productos mostrados: {count}',
    a11yChatMessages: 'Mensajes del asistente de compras',
    a11yCameraPreview: 'Vista previa de la cámara: apunta al artículo para buscar',
    a11ySuggestedReplies: 'Respuestas sugeridas',
    a11yViewProduct: 'Ver producto',
    a11yStartVoiceInput: 'Iniciar entrada de voz',
    a11yStopVoiceInput: 'Detener grabación y enviar',
    a11yTranscribingVoice: 'Transcribiendo mensaje de voz',
    a11yEnableVoiceReading: 'Activar lectura en voz alta',
    a11yDisableVoiceReading: 'Desactivar lectura en voz alta',
    voiceInputError: 'Entrada de voz no disponible',
    showMore: 'Mostrar más...',
    nowDescribing: 'Describiendo ahora',
    holdMicToRecord: 'Mantén presionado el micrófono para grabar',
    a11yAddImage: 'Agregar imagen',
    a11yListening: 'Escuchando',
    a11yHoldMicInstructions: 'Mantén presionado, o mantén presionada la barra espaciadora o Enter, para grabar. Suelta para enviar.',
    a11yCameraError: 'Cámara no disponible: verifique los permisos o intente cambiar de cámara',
    a11yMinimizeShoppingAssistant: 'Minimizar asistente de compras',
  },
  fr: {
    widgetTitle: 'Assistant de style',
    openingMessage1: 'Commençons',
    openingMessage2: 'Parlez-nous de vos besoins en matière de style et nous vous aiderons à trouver l\'article parfait pour vous',
    chatBoxPlaceholder: 'Tapez votre message',
    triggerCTA: 'Assistant de style',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de réduction',
    addToCart: 'Ajouter au panier',
    a11yStartNewChat: 'Démarrer un nouveau chat',
    a11yCloseShoppingAssistant: 'Fermer l\'assistant shopping',
    a11yCloseCamera: 'Fermer la caméra',
    a11yTakePhoto: 'Prendre une photo',
    a11ySwitchCamera: 'Changer de caméra',
    a11yOpenCamera: 'Ouvrir la caméra',
    a11yUploadImage: 'Importer une image',
    a11ySendMessage: 'Envoyer le message',
    a11yScrollToLatestMessage: 'Aller au dernier message',
    a11yCameraDrawer: 'Caméra',
    a11yChatInput: 'Tapez votre message à l\'assistant shopping',
    a11yUploadedImage: 'Image importée',
    a11yAssistantThinking: 'L\'assistant réfléchit',
    a11yProductResultsShown: 'Résultats de produits affichés : {count}',
    a11yChatMessages: 'Messages de l\'assistant shopping',
    a11yCameraPreview: 'Aperçu de la caméra — pointez vers l\'article à rechercher',
    a11ySuggestedReplies: 'Réponses suggérées',
    a11yViewProduct: 'Voir le produit',
    a11yStartVoiceInput: 'Démarrer la saisie vocale',
    a11yStopVoiceInput: 'Arrêter l\'enregistrement et envoyer',
    a11yTranscribingVoice: 'Transcription du message vocal',
    a11yEnableVoiceReading: 'Activer la lecture vocale',
    a11yDisableVoiceReading: 'Désactiver la lecture vocale',
    voiceInputError: 'Saisie vocale indisponible',
    showMore: 'Afficher plus...',
    nowDescribing: 'En cours de description',
    holdMicToRecord: 'Maintenez le micro enfoncé pour enregistrer',
    a11yAddImage: 'Ajouter une image',
    a11yListening: 'Écoute en cours',
    a11yHoldMicInstructions: 'Appuyez et maintenez, ou appuyez et maintenez Espace ou Entrée, pour enregistrer. Relâchez pour envoyer.',
    a11yCameraError: 'Caméra indisponible : vérifiez les autorisations ou essayez de changer de caméra',
    a11yMinimizeShoppingAssistant: 'Réduire l\'assistant shopping',
  },
  pt: {
    widgetTitle: 'Assistente de estilo',
    openingMessage1: 'Vamos começar',
    openingMessage2: 'Conte-nos sobre suas necessidades de estilo e nós o ajudaremos a encontrar o item perfeito para você',
    chatBoxPlaceholder: 'Digite sua mensagem',
    triggerCTA: 'Assistente de estilo',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de desconto',
    addToCart: 'Adicionar ao carrinho',
    a11yStartNewChat: 'Iniciar novo chat',
    a11yCloseShoppingAssistant: 'Fechar assistente de compras',
    a11yCloseCamera: 'Fechar câmera',
    a11yTakePhoto: 'Tirar foto',
    a11ySwitchCamera: 'Alternar câmera',
    a11yOpenCamera: 'Abrir câmera',
    a11yUploadImage: 'Enviar imagem',
    a11ySendMessage: 'Enviar mensagem',
    a11yScrollToLatestMessage: 'Ir para a mensagem mais recente',
    a11yCameraDrawer: 'Câmera',
    a11yChatInput: 'Digite sua mensagem para o assistente de compras',
    a11yUploadedImage: 'Imagem enviada',
    a11yAssistantThinking: 'O assistente está pensando',
    a11yProductResultsShown: 'Resultados de produtos exibidos: {count}',
    a11yChatMessages: 'Mensagens do assistente de compras',
    a11yCameraPreview: 'Pré-visualização da câmera — aponte para o item para pesquisar',
    a11ySuggestedReplies: 'Respostas sugeridas',
    a11yViewProduct: 'Ver produto',
    a11yStartVoiceInput: 'Iniciar entrada de voz',
    a11yStopVoiceInput: 'Parar gravação e enviar',
    a11yTranscribingVoice: 'Transcrevendo mensagem de voz',
    a11yEnableVoiceReading: 'Ativar leitura em voz alta',
    a11yDisableVoiceReading: 'Desativar leitura em voz alta',
    voiceInputError: 'Entrada de voz indisponível',
    showMore: 'Mostrar mais...',
    nowDescribing: 'Descrevendo agora',
    holdMicToRecord: 'Mantenha o microfone pressionado para gravar',
    a11yAddImage: 'Adicionar imagem',
    a11yListening: 'Ouvindo',
    a11yHoldMicInstructions: 'Pressione e segure, ou pressione e segure Espaço ou Enter, para gravar. Solte para enviar.',
    a11yCameraError: 'Câmera indisponível: verifique as permissões ou tente trocar de câmera',
    a11yMinimizeShoppingAssistant: 'Minimizar assistente de compras',
  },
  de: {
    widgetTitle: 'Stil-Assistent',
    openingMessage1: 'Los geht\'s',
    openingMessage2: 'Erzähl uns von deinen Styling-Bedürfnissen und wir helfen dir, das perfekte Teil für dich zu finden',
    chatBoxPlaceholder: 'Gib deine Nachricht ein',
    triggerCTA: 'Stil-Assistent',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} Rabatt',
    addToCart: 'In den Warenkorb',
    a11yStartNewChat: 'Neuen Chat starten',
    a11yCloseShoppingAssistant: 'Shopping-Assistent schließen',
    a11yCloseCamera: 'Kamera schließen',
    a11yTakePhoto: 'Foto aufnehmen',
    a11ySwitchCamera: 'Kamera wechseln',
    a11yOpenCamera: 'Kamera öffnen',
    a11yUploadImage: 'Bild hochladen',
    a11ySendMessage: 'Nachricht senden',
    a11yScrollToLatestMessage: 'Zur neuesten Nachricht scrollen',
    a11yCameraDrawer: 'Kamera',
    a11yChatInput: 'Nachricht an den Shopping-Assistenten eingeben',
    a11yUploadedImage: 'Hochgeladenes Bild',
    a11yAssistantThinking: 'Der Assistent denkt nach',
    a11yProductResultsShown: 'Angezeigte Produktergebnisse: {count}',
    a11yChatMessages: 'Nachrichten des Shopping-Assistenten',
    a11yCameraPreview: 'Kameravorschau – richten Sie sie auf den zu suchenden Artikel',
    a11ySuggestedReplies: 'Vorgeschlagene Antworten',
    a11yViewProduct: 'Produkt ansehen',
    a11yStartVoiceInput: 'Spracheingabe starten',
    a11yStopVoiceInput: 'Aufnahme beenden und senden',
    a11yTranscribingVoice: 'Sprachnachricht wird transkribiert',
    a11yEnableVoiceReading: 'Sprachausgabe aktivieren',
    a11yDisableVoiceReading: 'Sprachausgabe deaktivieren',
    voiceInputError: 'Spracheingabe nicht verfügbar',
    showMore: 'Mehr anzeigen...',
    nowDescribing: 'Wird jetzt beschrieben',
    holdMicToRecord: 'Mikrofon gedrückt halten, um aufzunehmen',
    a11yAddImage: 'Bild hinzufügen',
    a11yListening: 'Hört zu',
    a11yHoldMicInstructions: 'Halten Sie gedrückt, oder halten Sie Leertaste oder Eingabetaste gedrückt, um aufzunehmen. Loslassen zum Senden.',
    a11yCameraError: 'Kamera nicht verfügbar – überprüfen Sie die Berechtigungen oder wechseln Sie die Kamera',
    a11yMinimizeShoppingAssistant: 'Shopping-Assistenten minimieren',
  },
  it: {
    widgetTitle: 'Assistente di stile',
    openingMessage1: 'Iniziamo',
    openingMessage2: 'Parlaci delle tue esigenze di stile e ti aiuteremo a trovare l\'articolo perfetto per te',
    chatBoxPlaceholder: 'Digita il tuo messaggio',
    triggerCTA: 'Assistente di stile',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} di sconto',
    addToCart: 'Aggiungi al carrello',
    a11yStartNewChat: 'Avvia nuova chat',
    a11yCloseShoppingAssistant: 'Chiudi assistente shopping',
    a11yCloseCamera: 'Chiudi fotocamera',
    a11yTakePhoto: 'Scatta foto',
    a11ySwitchCamera: 'Cambia fotocamera',
    a11yOpenCamera: 'Apri fotocamera',
    a11yUploadImage: 'Carica immagine',
    a11ySendMessage: 'Invia messaggio',
    a11yScrollToLatestMessage: 'Vai al messaggio più recente',
    a11yCameraDrawer: 'Fotocamera',
    a11yChatInput: 'Digita il tuo messaggio per l\'assistente shopping',
    a11yUploadedImage: 'Immagine caricata',
    a11yAssistantThinking: 'L\'assistente sta pensando',
    a11yProductResultsShown: 'Risultati prodotto mostrati: {count}',
    a11yChatMessages: 'Messaggi dell\'assistente shopping',
    a11yCameraPreview: 'Anteprima della fotocamera: inquadra l\'articolo da cercare',
    a11ySuggestedReplies: 'Risposte suggerite',
    a11yViewProduct: 'Visualizza prodotto',
    a11yStartVoiceInput: 'Avvia input vocale',
    a11yStopVoiceInput: 'Interrompi registrazione e invia',
    a11yTranscribingVoice: 'Trascrizione del messaggio vocale',
    a11yEnableVoiceReading: 'Attiva lettura vocale',
    a11yDisableVoiceReading: 'Disattiva lettura vocale',
    voiceInputError: 'Input vocale non disponibile',
    showMore: 'Mostra altro...',
    nowDescribing: 'Descrizione in corso',
    holdMicToRecord: 'Tieni premuto il microfono per registrare',
    a11yAddImage: 'Aggiungi immagine',
    a11yListening: 'Ascolto in corso',
    a11yHoldMicInstructions: 'Tieni premuto, oppure tieni premuto Spazio o Invio, per registrare. Rilascia per inviare.',
    a11yCameraError: 'Fotocamera non disponibile: controlla le autorizzazioni o prova a cambiare fotocamera',
    a11yMinimizeShoppingAssistant: 'Riduci assistente shopping',
  },
  pl: {
    widgetTitle: 'Asystent Stylu',
    openingMessage1: 'Zacznijmy',
    openingMessage2: 'Powiedz nam, jakie masz potrzeby stylizacyjne, a pomożemy Ci znaleźć idealny produkt',
    chatBoxPlaceholder: 'Wpisz swoją wiadomość',
    triggerCTA: 'Asystent Stylu',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} zniżki',
    addToCart: 'Dodaj do koszyka',
    a11yStartNewChat: 'Rozpocznij nowy czat',
    a11yCloseShoppingAssistant: 'Zamknij asystenta zakupów',
    a11yCloseCamera: 'Zamknij aparat',
    a11yTakePhoto: 'Zrób zdjęcie',
    a11ySwitchCamera: 'Przełącz aparat',
    a11yOpenCamera: 'Otwórz aparat',
    a11yUploadImage: 'Prześlij obraz',
    a11ySendMessage: 'Wyślij wiadomość',
    a11yScrollToLatestMessage: 'Przejdź do najnowszej wiadomości',
    a11yCameraDrawer: 'Aparat',
    a11yChatInput: 'Wpisz wiadomość do asystenta zakupów',
    a11yUploadedImage: 'Przesłany obraz',
    a11yAssistantThinking: 'Asystent myśli',
    a11yProductResultsShown: 'Wyświetlone wyniki produktów: {count}',
    a11yChatMessages: 'Wiadomości asystenta zakupów',
    a11yCameraPreview: 'Podgląd kamery — skieruj ją na przedmiot, aby wyszukać',
    a11ySuggestedReplies: 'Sugerowane odpowiedzi',
    a11yViewProduct: 'Zobacz produkt',
    a11yStartVoiceInput: 'Rozpocznij wprowadzanie głosowe',
    a11yStopVoiceInput: 'Zatrzymaj nagrywanie i wyślij',
    a11yTranscribingVoice: 'Transkrypcja wiadomości głosowej',
    a11yEnableVoiceReading: 'Włącz odczytywanie głosowe',
    a11yDisableVoiceReading: 'Wyłącz odczytywanie głosowe',
    voiceInputError: 'Wprowadzanie głosowe niedostępne',
    showMore: 'Pokaż więcej...',
    nowDescribing: 'Teraz opisywane',
    holdMicToRecord: 'Przytrzymaj mikrofon, aby nagrywać',
    a11yAddImage: 'Dodaj obraz',
    a11yListening: 'Słucham',
    a11yHoldMicInstructions: 'Przytrzymaj lub przytrzymaj spację albo Enter, aby nagrywać. Zwolnij, aby wysłać.',
    a11yCameraError: 'Aparat niedostępny – sprawdź uprawnienia lub spróbuj zmienić aparat',
    a11yMinimizeShoppingAssistant: 'Zminimalizuj asystenta zakupów',
  },
  ko: {
    widgetTitle: '쇼핑 어시스턴트',
    openingMessage1: '시작해 볼까요?',
    openingMessage2: '스타일링에 필요한 것을 알려주시면 딱 맞는 상품을 찾아드릴게요',
    chatBoxPlaceholder: '메시지를 입력하세요',
    triggerCTA: '스타일 어시스턴트',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 할인',
    addToCart: '장바구니에 추가',
    a11yStartNewChat: '새 채팅 시작',
    a11yCloseShoppingAssistant: '쇼핑 어시스턴트 닫기',
    a11yCloseCamera: '카메라 닫기',
    a11yTakePhoto: '사진 찍기',
    a11ySwitchCamera: '카메라 전환',
    a11yOpenCamera: '카메라 열기',
    a11yUploadImage: '이미지 업로드',
    a11ySendMessage: '메시지 보내기',
    a11yScrollToLatestMessage: '최신 메시지로 이동',
    a11yCameraDrawer: '카메라',
    a11yChatInput: '쇼핑 어시스턴트에게 보낼 메시지를 입력하세요',
    a11yUploadedImage: '업로드된 이미지',
    a11yAssistantThinking: '어시스턴트가 생각 중입니다',
    a11yProductResultsShown: '표시된 상품 결과: {count}',
    a11yChatMessages: '쇼핑 어시스턴트 메시지',
    a11yCameraPreview: '카메라 미리보기 — 검색할 항목을 향하게 하세요',
    a11ySuggestedReplies: '추천 답변',
    a11yViewProduct: '상품 보기',
    a11yStartVoiceInput: '음성 입력 시작',
    a11yStopVoiceInput: '녹음 중지 및 전송',
    a11yTranscribingVoice: '음성 메시지 변환 중',
    a11yEnableVoiceReading: '음성 읽기 켜기',
    a11yDisableVoiceReading: '음성 읽기 끄기',
    voiceInputError: '음성 입력을 사용할 수 없습니다',
    showMore: '더 보기...',
    nowDescribing: '지금 설명 중',
    holdMicToRecord: '마이크를 길게 눌러 녹음하세요',
    a11yAddImage: '이미지 추가',
    a11yListening: '듣는 중',
    a11yHoldMicInstructions: '녹음하려면 길게 누르거나 스페이스바 또는 엔터 키를 길게 누르세요. 놓으면 전송됩니다.',
    a11yCameraError: '카메라를 사용할 수 없습니다 — 권한을 확인하거나 카메라를 전환해 보세요',
    a11yMinimizeShoppingAssistant: '쇼핑 어시스턴트 최소화',
  },
  ja: {
    widgetTitle: 'スタイルアシスタント',
    openingMessage1: '始めましょう',
    openingMessage2: 'スタイリングのニーズについて教えてください。あなたにぴったりのアイテムを見つけるお手伝いをします',
    chatBoxPlaceholder: 'メッセージを入力してください',
    triggerCTA: 'スタイルアシスタント',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 割引',
    addToCart: 'カートに追加',
    a11yStartNewChat: '新しいチャットを開始',
    a11yCloseShoppingAssistant: 'ショッピングアシスタントを閉じる',
    a11yCloseCamera: 'カメラを閉じる',
    a11yTakePhoto: '写真を撮る',
    a11ySwitchCamera: 'カメラを切り替える',
    a11yOpenCamera: 'カメラを開く',
    a11yUploadImage: '画像をアップロード',
    a11ySendMessage: 'メッセージを送信',
    a11yScrollToLatestMessage: '最新メッセージへ移動',
    a11yCameraDrawer: 'カメラ',
    a11yChatInput: 'ショッピングアシスタントへのメッセージを入力',
    a11yUploadedImage: 'アップロードされた画像',
    a11yAssistantThinking: 'アシスタントが考えています',
    a11yProductResultsShown: '表示された商品結果: {count}',
    a11yChatMessages: 'ショッピングアシスタントのメッセージ',
    a11yCameraPreview: 'カメラプレビュー — 検索する商品にカメラを向けてください',
    a11ySuggestedReplies: '候補の返信',
    a11yViewProduct: '商品を見る',
    a11yStartVoiceInput: '音声入力を開始',
    a11yStopVoiceInput: '録音を停止して送信',
    a11yTranscribingVoice: '音声メッセージを文字起こし中',
    a11yEnableVoiceReading: '音声読み上げをオン',
    a11yDisableVoiceReading: '音声読み上げをオフ',
    voiceInputError: '音声入力は利用できません',
    showMore: 'もっと見る...',
    nowDescribing: '説明中',
    holdMicToRecord: 'マイクを長押しして録音',
    a11yAddImage: '画像を追加',
    a11yListening: '聞いています',
    a11yHoldMicInstructions: '録音するには長押しするか、スペースキーまたはEnterキーを長押ししてください。離すと送信されます。',
    a11yCameraError: 'カメラを利用できません — 権限を確認するか、カメラの切り替えをお試しください',
    a11yMinimizeShoppingAssistant: 'ショッピングアシスタントを最小化',
  },
  th: {
    widgetTitle: 'ช่วยเหลือสินค้า',
    openingMessage1: 'มาเริ่มกันเลย',
    openingMessage2: 'บอกเราเกี่ยวกับความต้องการด้านสไตล์ของคุณ แล้วเราจะช่วยคุณค้นหาสินค้าที่สมบูรณ์แบบสำหรับคุณ',
    chatBoxPlaceholder: 'พิมพ์ข้อความของคุณ',
    triggerCTA: 'ผู้ช่วยด้านสไตล์',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: 'ลดราคา {discount}',
    addToCart: 'เพิ่มสินค้าลงตะกร้า',
    a11yStartNewChat: 'เริ่มแชทใหม่',
    a11yCloseShoppingAssistant: 'ปิดผู้ช่วยช้อปปิ้ง',
    a11yCloseCamera: 'ปิดกล้อง',
    a11yTakePhoto: 'ถ่ายรูป',
    a11ySwitchCamera: 'สลับกล้อง',
    a11yOpenCamera: 'เปิดกล้อง',
    a11yUploadImage: 'อัปโหลดรูปภาพ',
    a11ySendMessage: 'ส่งข้อความ',
    a11yScrollToLatestMessage: 'ไปยังข้อความล่าสุด',
    a11yCameraDrawer: 'กล้อง',
    a11yChatInput: 'พิมพ์ข้อความของคุณถึงผู้ช่วยช้อปปิ้ง',
    a11yUploadedImage: 'รูปภาพที่อัปโหลด',
    a11yAssistantThinking: 'ผู้ช่วยกำลังคิด',
    a11yProductResultsShown: 'แสดงผลลัพธ์สินค้า: {count}',
    a11yChatMessages: 'ข้อความผู้ช่วยช้อปปิ้ง',
    a11yCameraPreview: 'ตัวอย่างกล้อง — เล็งไปที่สินค้าที่ต้องการค้นหา',
    a11ySuggestedReplies: 'คำตอบที่แนะนำ',
    a11yViewProduct: 'ดูสินค้า',
    a11yStartVoiceInput: 'เริ่มป้อนข้อมูลด้วยเสียง',
    a11yStopVoiceInput: 'หยุดบันทึกและส่ง',
    a11yTranscribingVoice: 'กำลังถอดเสียงข้อความ',
    a11yEnableVoiceReading: 'เปิดการอ่านข้อความด้วยเสียง',
    a11yDisableVoiceReading: 'ปิดการอ่านข้อความด้วยเสียง',
    voiceInputError: 'ไม่สามารถใช้การป้อนด้วยเสียงได้',
    showMore: 'แสดงเพิ่มเติม...',
    nowDescribing: 'กำลังอธิบาย',
    holdMicToRecord: 'กดค้างที่ไมโครโฟนเพื่อบันทึกเสียง',
    a11yAddImage: 'เพิ่มรูปภาพ',
    a11yListening: 'กำลังฟัง',
    a11yHoldMicInstructions: 'กดค้างไว้ หรือกดค้างที่ Space หรือ Enter เพื่อบันทึกเสียง ปล่อยเพื่อส่ง',
    a11yCameraError: 'ไม่สามารถใช้กล้องได้ — ตรวจสอบสิทธิ์การเข้าถึงหรือลองสลับกล้อง',
    a11yMinimizeShoppingAssistant: 'ย่อผู้ช่วยช้อปปิ้ง',
  },
  zh: {
    widgetTitle: '购物助手',
    openingMessage1: '我们开始吧',
    openingMessage2: '告诉我们您的造型需求，我们会帮您找到合适的商品',
    chatBoxPlaceholder: '输入您的消息',
    triggerCTA: '聊天',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 折扣',
    addToCart: '加入购物车',
    a11yStartNewChat: '开始新聊天',
    a11yCloseShoppingAssistant: '关闭购物助手',
    a11yCloseCamera: '关闭相机',
    a11yTakePhoto: '拍照',
    a11ySwitchCamera: '切换相机',
    a11yOpenCamera: '打开相机',
    a11yUploadImage: '上传图片',
    a11ySendMessage: '发送消息',
    a11yScrollToLatestMessage: '转到最新消息',
    a11yCameraDrawer: '相机',
    a11yChatInput: '输入给购物助手的消息',
    a11yUploadedImage: '已上传的图片',
    a11yAssistantThinking: '助手正在思考',
    a11yProductResultsShown: '已显示商品结果：{count}',
    a11yChatMessages: '购物助手消息',
    a11yCameraPreview: '相机预览 — 将镜头对准要搜索的商品',
    a11ySuggestedReplies: '推荐回复',
    a11yViewProduct: '查看商品',
    a11yStartVoiceInput: '开始语音输入',
    a11yStopVoiceInput: '停止录音并发送',
    a11yTranscribingVoice: '正在转写语音消息',
    a11yEnableVoiceReading: '开启语音朗读',
    a11yDisableVoiceReading: '关闭语音朗读',
    voiceInputError: '语音输入不可用',
    showMore: '显示更多...',
    nowDescribing: '正在描述',
    holdMicToRecord: '按住麦克风进行录音',
    a11yAddImage: '添加图片',
    a11yListening: '正在聆听',
    a11yHoldMicInstructions: '按住，或按住空格键或回车键进行录音。松开即可发送。',
    a11yCameraError: '相机不可用 — 请检查权限或尝试切换相机',
    a11yMinimizeShoppingAssistant: '最小化购物助手',
  },
};

export const DEFAULT_CUSTOMIZATIONS: WidgetConfig['customizations'] = {
  // useChat's playGreeting only speaks the opening greeting when this is true — without it, the
  // opening message would silently stop being narrated for any host that already has
  // customizations.chatbot.voiceEnabled on, since this widget previously spoke the opening
  // whenever voice reading was enabled at all, with no separate greeting-specific gate.
  chatbot: {
    voiceGreetingEnabled: true,
  },
  breakpoints: {
    mobile: {
      maxWidth: 767,
    },
    tablet: {
      maxWidth: 1023,
    },
  },
  productGrid: {
    mobile: {
      productsPerRow: 2,
      marginVertical: 0,
      marginHorizontal: 8,
    },
    tablet: {
      productsPerRow: 2,
      marginVertical: 0,
      marginHorizontal: 8,
    },
    desktop: {
      productsPerRow: 2,
      marginVertical: 0,
      marginHorizontal: 8,
    },
  },
  productCard: {
    imageAspectRatio: '2 / 3',
    openLinksInNewTab: false,
    price: {
      show: true,
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
      fontColor: '#B91C1C',
      fontColorDark: '#EF4444',
    },
    originalPrice: {
      show: true,
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
      fontColor: '#6B7280',
      fontColorDark: '#9CA3AF',
      position: 'AFTER',
      strikethrough: true,
    },
    discount: {
      show: false,
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
      fontColor: '#EF4444',
      fontColorDark: '#EF4444',
      showPercentage: true,
      rounding: 1,
    },
    title: {
      show: true,
      fieldSource: 'title',
      font: {
        mobile: {
          size: 14,
          weight: 700,
        },
        tablet: {
          size: 14,
          weight: 700,
        },
        desktop: {
          size: 16,
          weight: 700,
        },
      },
    },
    secondaryTitle: {
      show: false,
      fieldSource: 'brand',
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
    },
    addToWishlist: {
      enable: false,
      position: 'top_right',
      iconInactive: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
      iconActive: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
    },
    addToCart: {
      enable: false,
      color: '#FFFFFF',
      colorDark: '#000000',
      backgroundColor: '#000000',
      backgroundColorDark: '#FFFFFF',
      layout: 'ICON_TEXT',
    },
    images: {
      mainImage: 'main',
      hoverImage: 'additional',
      showAlternatives: false,
    },
  },
  buttons: {
    primary: {
      fontColor: '#000000',
      fontColorDark: '#616161',
      backgroundColor: '#FFFFFF',
      backgroundColorDark: '#FFFFFF',
    },
    secondary: {
      fontColor: '#FFFFFF',
      fontColorDark: '#000000',
      backgroundColor: '#000000',
      backgroundColorDark: '#FFFFFF',
    },
  },
  generalLayout: {
    headingFont: {
      mobile: {
        size: 16,
        weight: 400,
      },
      tablet: {
        size: 16,
        weight: 400,
      },
      desktop: {
        size: 16,
        weight: 400,
      },
    },
    bodyFont: {
      mobile: {
        size: 14,
        weight: 400,
      },
      tablet: {
        size: 14,
        weight: 400,
      },
      desktop: {
        size: 16,
        weight: 400,
      },
    },
    fontFamily: '',
    fontColor: '#000000',
    fontColorDark: '#FFFFFF',
    backgroundColor: '#FFFFFF',
    backgroundColorDark: '#000000',
    showWidgetTitle: true,
    showViSenzeLogo: false,
    darkModeDefault: false,
  },
  popup: {
    position: 'left',
    layout: 'docked',
    triggerIcon: {
      layout: 'ICON',
      color: '#000000',
      colorDark: '#FFFFFF',
      backgroundColor: '#FFFFFF',
      backgroundColorDark: '#000000',
      hide: false,
    },
    floating: {
      width: 380,
      height: 580,
      header: {
        backgroundColor: '#4F46E5',
        backgroundColorDark: '#4338CA',
        gradientToColor: '#7C3AED',
        gradientToColorDark: '#6D28D9',
      },
    },
  },
};
