import type { WidgetConfig } from '../../common/wigmix-core';
import type { LanguagePack } from '../../common/locales/locale';

export const DEFAULT_TEXTS: LanguagePack = {
  en: {
    widgetTitle: 'Shopping Assistant',
    openingMessage1: 'Let\'s get started',
    openingMessage2: 'Tell us about what your styling needs and we will help you find the perfect item for you',
    chatBoxPlaceholder: 'Type your message',
    triggerCTA: 'Style Assistant',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} off',
    addToCart: 'Add to Cart',
    a11yStartNewChat: 'Start new chat',
    a11yCloseShoppingAssistant: 'Close shopping assistant',
    a11yCloseCamera: 'Close camera',
    a11yTakePhoto: 'Take photo',
    a11ySwitchCamera: 'Switch camera',
    a11yOpenCamera: 'Open camera',
    a11yUploadImage: 'Upload image',
    a11ySendMessage: 'Send message',
    a11yScrollToLatestMessage: 'Scroll to latest message',
    a11yCameraDrawer: 'Camera',
    showMore: 'Show more...',
  },
  es: {
    widgetTitle: 'Asistente de estilo',
    openingMessage1: 'Empecemos',
    openingMessage2: 'Cuéntanos sobre tus necesidades de estilo y te ayudaremos a encontrar el artículo perfecto para ti',
    chatBoxPlaceholder: 'Escribe tu mensaje',
    triggerCTA: 'Asistente de estilo',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de descuento',
    addToCart: 'Agregar al carrito',
    a11yStartNewChat: 'Iniciar nuevo chat',
    a11yCloseShoppingAssistant: 'Cerrar asistente de compras',
    a11yCloseCamera: 'Cerrar camara',
    a11yTakePhoto: 'Tomar foto',
    a11ySwitchCamera: 'Cambiar camara',
    a11yOpenCamera: 'Abrir camara',
    a11yUploadImage: 'Subir imagen',
    a11ySendMessage: 'Enviar mensaje',
    a11yScrollToLatestMessage: 'Ir al mensaje mas reciente',
    a11yCameraDrawer: 'Camara',
    showMore: 'Mostrar mas...',
  },
  fr: {
    widgetTitle: 'Assistant de style',
    openingMessage1: 'Commençons',
    openingMessage2: 'Parlez-nous de vos besoins en matière de style et nous vous aiderons à trouver l\'article parfait pour vous',
    chatBoxPlaceholder: 'Tapez votre message',
    triggerCTA: 'Assistant de style',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de réduction',
    addToCart: 'Ajouter au panier',
    a11yStartNewChat: 'Demarrer un nouveau chat',
    a11yCloseShoppingAssistant: 'Fermer l assistant shopping',
    a11yCloseCamera: 'Fermer la camera',
    a11yTakePhoto: 'Prendre une photo',
    a11ySwitchCamera: 'Changer de camera',
    a11yOpenCamera: 'Ouvrir la camera',
    a11yUploadImage: 'Importer une image',
    a11ySendMessage: 'Envoyer le message',
    a11yScrollToLatestMessage: 'Aller au dernier message',
    a11yCameraDrawer: 'Camera',
    showMore: 'Afficher plus...',
  },
  pt: {
    widgetTitle: 'Assistente de estilo',
    openingMessage1: 'Vamos começar',
    openingMessage2: 'Conte-nos sobre suas necessidades de estilo e nós o ajudaremos a encontrar o item perfeito para você',
    chatBoxPlaceholder: 'Digite sua mensagem',
    triggerCTA: 'Assistente de estilo',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de desconto',
    addToCart: 'Adicionar ao carrinho',
    a11yStartNewChat: 'Iniciar novo chat',
    a11yCloseShoppingAssistant: 'Fechar assistente de compras',
    a11yCloseCamera: 'Fechar camera',
    a11yTakePhoto: 'Tirar foto',
    a11ySwitchCamera: 'Alternar camera',
    a11yOpenCamera: 'Abrir camera',
    a11yUploadImage: 'Enviar imagem',
    a11ySendMessage: 'Enviar mensagem',
    a11yScrollToLatestMessage: 'Ir para a mensagem mais recente',
    a11yCameraDrawer: 'Camera',
    showMore: 'Mostrar mais...',
  },
  de: {
    widgetTitle: 'Stil-Assistent',
    openingMessage1: 'Los geht\'s',
    openingMessage2: 'Erzähl uns von deinen Styling-Bedürfnissen und wir helfen dir, das perfekte Teil für dich zu finden',
    chatBoxPlaceholder: 'Gib deine Nachricht ein',
    triggerCTA: 'Stil-Assistent',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} Rabatt',
    addToCart: 'In den Warenkorb',
    a11yStartNewChat: 'Neuen Chat starten',
    a11yCloseShoppingAssistant: 'Shopping-Assistent schliessen',
    a11yCloseCamera: 'Kamera schliessen',
    a11yTakePhoto: 'Foto aufnehmen',
    a11ySwitchCamera: 'Kamera wechseln',
    a11yOpenCamera: 'Kamera offnen',
    a11yUploadImage: 'Bild hochladen',
    a11ySendMessage: 'Nachricht senden',
    a11yScrollToLatestMessage: 'Zur neuesten Nachricht scrollen',
    a11yCameraDrawer: 'Kamera',
    showMore: 'Mehr anzeigen...',
  },
  it: {
    widgetTitle: 'Assistente di stile',
    openingMessage1: 'Iniziamo',
    openingMessage2: 'Parlaci delle tue esigenze di stile e ti aiuteremo a trovare l\'articolo perfetto per te',
    chatBoxPlaceholder: 'Digita il tuo messaggio',
    triggerCTA: 'Assistente di stile',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} di sconto',
    addToCart: 'Aggiungi al carrello',
    a11yStartNewChat: 'Avvia nuova chat',
    a11yCloseShoppingAssistant: 'Chiudi assistente shopping',
    a11yCloseCamera: 'Chiudi fotocamera',
    a11yTakePhoto: 'Scatta foto',
    a11ySwitchCamera: 'Cambia fotocamera',
    a11yOpenCamera: 'Apri fotocamera',
    a11yUploadImage: 'Carica immagine',
    a11ySendMessage: 'Invia messaggio',
    a11yScrollToLatestMessage: 'Vai al messaggio piu recente',
    a11yCameraDrawer: 'Fotocamera',
    showMore: 'Mostra altro...',
  },
  pl: {
    widgetTitle: 'Asystent Stylu',
    openingMessage1: 'Zacznijmy',
    openingMessage2: 'Powiedz nam, jakie masz potrzeby stylizacyjne, a pomożemy Ci znaleźć idealny produkt',
    chatBoxPlaceholder: 'Wpisz swoją wiadomość',
    triggerCTA: 'Asystent Stylu',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} zniżki',
    addToCart: 'Dodaj do koszyka',
    a11yStartNewChat: 'Rozpocznij nowy czat',
    a11yCloseShoppingAssistant: 'Zamknij asystenta zakupow',
    a11yCloseCamera: 'Zamknij aparat',
    a11yTakePhoto: 'Zrob zdjecie',
    a11ySwitchCamera: 'Przelacz aparat',
    a11yOpenCamera: 'Otworz aparat',
    a11yUploadImage: 'Przeslij obraz',
    a11ySendMessage: 'Wyslij wiadomosc',
    a11yScrollToLatestMessage: 'Przejdz do najnowszej wiadomosci',
    a11yCameraDrawer: 'Aparat',
    showMore: 'Pokaz wiecej...',
  },
  ko: {
    widgetTitle: '쇼핑 어시스턴트',
    openingMessage1: '시작해 볼까요?',
    openingMessage2: '스타일링에 필요한 것을 알려주시면 딱 맞는 상품을 찾아드릴게요',
    chatBoxPlaceholder: '메시지를 입력하세요',
    triggerCTA: '스타일 어시스턴트',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 할인',
    addToCart: '장바구니에 추가',
    a11yStartNewChat: '새 채팅 시작',
    a11yCloseShoppingAssistant: '쇼핑 어시스턴트 닫기',
    a11yCloseCamera: '카메라 닫기',
    a11yTakePhoto: '사진 찍기',
    a11ySwitchCamera: '카메라 전환',
    a11yOpenCamera: '카메라 열기',
    a11yUploadImage: '이미지 업로드',
    a11ySendMessage: '메시지 보내기',
    a11yScrollToLatestMessage: '최신 메시지로 이동',
    a11yCameraDrawer: '카메라',
    showMore: '더 보기...',
  },
  ja: {
    widgetTitle: 'スタイルアシスタント',
    openingMessage1: '始めましょう',
    openingMessage2: 'スタイリングのニーズについて教えてください。あなたにぴったりのアイテムを見つけるお手伝いをします',
    chatBoxPlaceholder: 'メッセージを入力してください',
    triggerCTA: 'スタイルアシスタント',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 割引',
    addToCart: 'カートに追加',
    a11yStartNewChat: '新しいチャットを開始',
    a11yCloseShoppingAssistant: 'ショッピングアシスタントを閉じる',
    a11yCloseCamera: 'カメラを閉じる',
    a11yTakePhoto: '写真を撮る',
    a11ySwitchCamera: 'カメラを切り替える',
    a11yOpenCamera: 'カメラを開く',
    a11yUploadImage: '画像をアップロード',
    a11ySendMessage: 'メッセージを送信',
    a11yScrollToLatestMessage: '最新メッセージへ移動',
    a11yCameraDrawer: 'カメラ',
    showMore: 'もっと見る...',
  },
  th: {
    widgetTitle: 'ช่วยเหลือสินค้า',
    openingMessage1: 'มาเริ่มกันเลย',
    openingMessage2: 'บอกเราเกี่ยวกับความต้องการด้านสไตล์ของคุณ แล้วเราจะช่วยคุณค้นหาสินค้าที่สมบูรณ์แบบสำหรับคุณ',
    chatBoxPlaceholder: 'พิมพ์ข้อความของคุณ',
    triggerCTA: 'ผู้ช่วยด้านสไตล์',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: 'ลดราคา {discount}',
    addToCart: 'เพิ่มสินค้าลงตะกร้า',
    a11yStartNewChat: 'เริ่มแชทใหม่',
    a11yCloseShoppingAssistant: 'ปิดผู้ช่วยช้อปปิ้ง',
    a11yCloseCamera: 'ปิดกล้อง',
    a11yTakePhoto: 'ถ่ายรูป',
    a11ySwitchCamera: 'สลับกล้อง',
    a11yOpenCamera: 'เปิดกล้อง',
    a11yUploadImage: 'อัปโหลดรูปภาพ',
    a11ySendMessage: 'ส่งข้อความ',
    a11yScrollToLatestMessage: 'ไปยังข้อความล่าสุด',
    a11yCameraDrawer: 'กล้อง',
    showMore: 'แสดงเพิ่มเติม...',
  },
  zh: {
    widgetTitle: '购物助手',
    openingMessage1: '我们开始吧',
    openingMessage2: '告诉我们您的造型需求，我们会帮您找到合适的商品',
    chatBoxPlaceholder: '输入您的消息',
    triggerCTA: '聊天',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 折扣',
    addToCart: '加入购物车',
    a11yStartNewChat: '开始新聊天',
    a11yCloseShoppingAssistant: '关闭购物助手',
    a11yCloseCamera: '关闭相机',
    a11yTakePhoto: '拍照',
    a11ySwitchCamera: '切换相机',
    a11yOpenCamera: '打开相机',
    a11yUploadImage: '上传图片',
    a11ySendMessage: '发送消息',
    a11yScrollToLatestMessage: '转到最新消息',
    a11yCameraDrawer: '相机',
    showMore: '显示更多...',
  },
};

export const DEFAULT_CUSTOMIZATIONS: WidgetConfig['customizations'] = {
  breakpoints: {
    mobile: {
      maxWidth: 767,
    },
    tablet: {
      maxWidth: 1023,
    },
  },
  productGrid: {
    mobile: {
      productsPerRow: 3,
      marginVertical: 0,
      marginHorizontal: 8,
    },
    tablet: {
      productsPerRow: 3,
      marginVertical: 0,
      marginHorizontal: 8,
    },
    desktop: {
      productsPerRow: 3,
      marginVertical: 0,
      marginHorizontal: 8,
    },
  },
  productCard: {
    imageAspectRatio: '2 / 3',
    openLinksInNewTab: false,
    price: {
      show: true,
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
      fontColor: '#EF4444',
      fontColorDark: '#EF4444',
    },
    originalPrice: {
      show: true,
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
      fontColor: '#9CA3AF',
      fontColorDark: '#9CA3AF',
      position: 'AFTER',
      strikethrough: true,
    },
    discount: {
      show: false,
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
      fontColor: '#EF4444',
      fontColorDark: '#EF4444',
      showPercentage: true,
      rounding: 1,
    },
    title: {
      show: true,
      fieldSource: 'title',
      font: {
        mobile: {
          size: 14,
          weight: 700,
        },
        tablet: {
          size: 14,
          weight: 700,
        },
        desktop: {
          size: 16,
          weight: 700,
        },
      },
    },
    secondaryTitle: {
      show: false,
      fieldSource: 'brand',
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
    },
    addToWishlist: {
      enable: false,
      position: 'top_right',
      iconInactive: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
      iconActive: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
    },
    addToCart: {
      enable: false,
      color: '#FFFFFF',
      colorDark: '#000000',
      backgroundColor: '#000000',
      backgroundColorDark: '#FFFFFF',
      layout: 'ICON_TEXT',
    },
    images: {
      mainImage: 'main',
      hoverImage: 'additional',
      showAlternatives: false,
    },
  },
  buttons: {
    primary: {
      fontColor: '#000000',
      fontColorDark: '#616161',
      backgroundColor: '#616161',
      backgroundColorDark: '#FFFFFF',
    },
    secondary: {
      fontColor: '#FFFFFF',
      fontColorDark: '#000000',
      backgroundColor: '#000000',
      backgroundColorDark: '#FFFFFF',
    },
  },
  generalLayout: {
    headingFont: {
      mobile: {
        size: 16,
        weight: 400,
      },
      tablet: {
        size: 16,
        weight: 400,
      },
      desktop: {
        size: 16,
        weight: 400,
      },
    },
    bodyFont: {
      mobile: {
        size: 14,
        weight: 400,
      },
      tablet: {
        size: 14,
        weight: 400,
      },
      desktop: {
        size: 16,
        weight: 400,
      },
    },
    fontFamily: '',
    fontColor: '#000000',
    fontColorDark: '#FFFFFF',
    backgroundColor: '#FFFFFF',
    backgroundColorDark: '#000000',
    showWidgetTitle: true,
    showViSenzeLogo: false,
    darkModeDefault: false,
  },
  popup: {
    position: 'left',
    triggerIcon: {
      layout: 'ICON',
      color: '#000000',
      colorDark: '#FFFFFF',
      backgroundColor: '#FFFFFF',
      backgroundColorDark: '#000000',
      hide: false,
    },
  },
};
