import type { WidgetConfig } from '../../common/wigmix-core';
import type { LanguagePack } from '../../common/locales/locale';

export const DEFAULT_TEXTS: LanguagePack = {
  en: {
    seeResults: 'See Results',
    noQueryProvided: 'No search query provided.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} off',
    addToCart: 'Add to Cart',
    gettingOverview: 'Thinking...',
    findingProducts: 'Finding products...',
    aiOverviewLabel: 'AI Overview',
    a11yProductResultsShown: '{count} products found',
    a11yAssistantThinking: 'Assistant is thinking',
    a11yChatMessages: 'Shopping assistant messages',
    a11yScrollToLatestMessage: 'Scroll to latest message',
    a11ySuggestedReplies: 'Suggested replies',
    a11yUploadedImage: 'Uploaded image',
    nowDescribing: 'Now Describing',
    showMore: 'Show more...',
    a11yCloseFullScreen: 'Close full screen',
    a11yEnableMute: 'Unmute voice output',
    a11yToggleMute: 'Mute voice output',
    a11yStartNewChat: 'Start new chat',
    a11yAddImage: 'Add image',
    a11yUploadImage: 'Upload an image to search',
    a11yOpenCamera: 'Open camera',
    a11yCameraDrawer: 'Camera',
    a11yCameraPreview: 'Camera preview — point at the item to search',
    a11yCloseCamera: 'Close camera',
    a11yTakePhoto: 'Take photo',
    a11ySwitchCamera: 'Switch camera',
    a11yCameraError: 'Camera unavailable — check permissions or try switching cameras',
    a11yStopVoiceInput: 'Stop recording and send',
    holdMicToRecord: 'Hold the mic to record',
    voiceInputError: 'Voice input unavailable',
    a11yChatInput: 'Type your message to the shopping assistant',
    chatBoxPlaceholder: 'Type your message',
    a11yTranscribingVoice: 'Transcribing voice message',
    a11yListening: 'Listening',
    a11yHoldMicInstructions: 'Press and hold, or press and hold Space or Enter, to record. Release to send.',
    a11ySendMessage: 'Send message',
  },
  es: {
    seeResults: 'Ver resultados',
    noQueryProvided: 'No se proporcionó ninguna consulta de búsqueda.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de descuento',
    addToCart: 'Agregar al carrito',
    gettingOverview: 'Pensando...',
    findingProducts: 'Buscando productos...',
    aiOverviewLabel: 'Resumen de IA',
    a11yProductResultsShown: '{count} productos encontrados',
    a11yAssistantThinking: 'El asistente está pensando',
    a11yChatMessages: 'Mensajes del asistente de compras',
    a11yScrollToLatestMessage: 'Desplazarse al último mensaje',
    a11ySuggestedReplies: 'Respuestas sugeridas',
    a11yUploadedImage: 'Imagen subida',
    nowDescribing: 'Describiendo ahora',
    showMore: 'Mostrar más...',
    a11yCloseFullScreen: 'Cerrar pantalla completa',
    a11yEnableMute: 'Activar salida de voz',
    a11yToggleMute: 'Silenciar salida de voz',
    a11yStartNewChat: 'Iniciar nuevo chat',
    a11yAddImage: 'Agregar imagen',
    a11yUploadImage: 'Subir una imagen para buscar',
    a11yOpenCamera: 'Abrir cámara',
    a11yCameraDrawer: 'Cámara',
    a11yCameraPreview: 'Vista previa de la cámara: apunta al artículo para buscar',
    a11yCloseCamera: 'Cerrar cámara',
    a11yTakePhoto: 'Tomar foto',
    a11ySwitchCamera: 'Cambiar cámara',
    a11yCameraError: 'Cámara no disponible: verifique los permisos o intente cambiar de cámara',
    a11yStopVoiceInput: 'Detener grabación y enviar',
    holdMicToRecord: 'Mantén presionado el micrófono para grabar',
    voiceInputError: 'Entrada de voz no disponible',
    a11yChatInput: 'Escribe tu mensaje al asistente de compras',
    chatBoxPlaceholder: 'Escribe tu mensaje',
    a11yTranscribingVoice: 'Transcribiendo mensaje de voz',
    a11yListening: 'Escuchando',
    a11yHoldMicInstructions: 'Mantén presionado, o mantén presionada la barra espaciadora o Enter, para grabar. Suelta para enviar.',
    a11ySendMessage: 'Enviar mensaje',
  },
  fr: {
    seeResults: 'Voir les résultats',
    noQueryProvided: 'Aucune requête de recherche fournie.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de réduction',
    addToCart: 'Ajouter au panier',
    gettingOverview: 'Réflexion en cours...',
    findingProducts: 'Recherche de produits...',
    aiOverviewLabel: 'Aperçu IA',
    a11yProductResultsShown: '{count} produits trouvés',
    a11yAssistantThinking: 'L\'assistant réfléchit',
    a11yChatMessages: 'Messages de l\'assistant shopping',
    a11yScrollToLatestMessage: 'Faire défiler jusqu\'au dernier message',
    a11ySuggestedReplies: 'Réponses suggérées',
    a11yUploadedImage: 'Image téléversée',
    nowDescribing: 'Description en cours',
    showMore: 'Afficher plus...',
    a11yCloseFullScreen: 'Fermer le plein écran',
    a11yEnableMute: 'Réactiver la sortie vocale',
    a11yToggleMute: 'Couper la sortie vocale',
    a11yStartNewChat: 'Démarrer une nouvelle discussion',
    a11yAddImage: 'Ajouter une image',
    a11yUploadImage: 'Téléverser une image pour rechercher',
    a11yOpenCamera: 'Ouvrir la caméra',
    a11yCameraDrawer: 'Caméra',
    a11yCameraPreview: 'Aperçu de la caméra — pointez vers l\'article à rechercher',
    a11yCloseCamera: 'Fermer la caméra',
    a11yTakePhoto: 'Prendre une photo',
    a11ySwitchCamera: 'Changer de caméra',
    a11yCameraError: 'Caméra indisponible : vérifiez les autorisations ou essayez de changer de caméra',
    a11yStopVoiceInput: 'Arrêter l\'enregistrement et envoyer',
    holdMicToRecord: 'Maintenez le micro enfoncé pour enregistrer',
    voiceInputError: 'Saisie vocale indisponible',
    a11yChatInput: 'Écrivez votre message à l\'assistant shopping',
    chatBoxPlaceholder: 'Écrivez votre message',
    a11yTranscribingVoice: 'Transcription du message vocal',
    a11yListening: 'Écoute en cours',
    a11yHoldMicInstructions: 'Appuyez et maintenez, ou appuyez et maintenez Espace ou Entrée, pour enregistrer. Relâchez pour envoyer.',
    a11ySendMessage: 'Envoyer le message',
  },
  pt: {
    seeResults: 'Ver resultados',
    noQueryProvided: 'Nenhuma consulta de pesquisa fornecida.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de desconto',
    addToCart: 'Adicionar ao carrinho',
    gettingOverview: 'Pensando...',
    findingProducts: 'Encontrando produtos...',
    aiOverviewLabel: 'Visão geral de IA',
    a11yProductResultsShown: '{count} produtos encontrados',
    a11yAssistantThinking: 'O assistente está pensando',
    a11yChatMessages: 'Mensagens do assistente de compras',
    a11yScrollToLatestMessage: 'Rolar até a última mensagem',
    a11ySuggestedReplies: 'Respostas sugeridas',
    a11yUploadedImage: 'Imagem enviada',
    nowDescribing: 'Descrevendo agora',
    showMore: 'Mostrar mais...',
    a11yCloseFullScreen: 'Fechar tela cheia',
    a11yEnableMute: 'Ativar saída de voz',
    a11yToggleMute: 'Silenciar saída de voz',
    a11yStartNewChat: 'Iniciar novo chat',
    a11yAddImage: 'Adicionar imagem',
    a11yUploadImage: 'Enviar uma imagem para pesquisar',
    a11yOpenCamera: 'Abrir câmera',
    a11yCameraDrawer: 'Câmera',
    a11yCameraPreview: 'Pré-visualização da câmera — aponte para o item para pesquisar',
    a11yCloseCamera: 'Fechar câmera',
    a11yTakePhoto: 'Tirar foto',
    a11ySwitchCamera: 'Alternar câmera',
    a11yCameraError: 'Câmera indisponível: verifique as permissões ou tente trocar de câmera',
    a11yStopVoiceInput: 'Parar gravação e enviar',
    holdMicToRecord: 'Mantenha o microfone pressionado para gravar',
    voiceInputError: 'Entrada de voz indisponível',
    a11yChatInput: 'Digite sua mensagem para o assistente de compras',
    chatBoxPlaceholder: 'Digite sua mensagem',
    a11yTranscribingVoice: 'Transcrevendo mensagem de voz',
    a11yListening: 'Ouvindo',
    a11yHoldMicInstructions: 'Pressione e segure, ou pressione e segure Espaço ou Enter, para gravar. Solte para enviar.',
    a11ySendMessage: 'Enviar mensagem',
  },
  de: {
    seeResults: 'Ergebnisse anzeigen',
    noQueryProvided: 'Keine Suchanfrage angegeben.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} Rabatt',
    addToCart: 'In den Warenkorb',
    gettingOverview: 'Denke nach...',
    findingProducts: 'Produkte werden gesucht...',
    aiOverviewLabel: 'KI-Übersicht',
    a11yProductResultsShown: '{count} Produkte gefunden',
    a11yAssistantThinking: 'Der Assistent denkt nach',
    a11yChatMessages: 'Nachrichten des Einkaufsassistenten',
    a11yScrollToLatestMessage: 'Zur neuesten Nachricht scrollen',
    a11ySuggestedReplies: 'Vorgeschlagene Antworten',
    a11yUploadedImage: 'Hochgeladenes Bild',
    nowDescribing: 'Wird jetzt beschrieben',
    showMore: 'Mehr anzeigen...',
    a11yCloseFullScreen: 'Vollbild schließen',
    a11yEnableMute: 'Sprachausgabe aktivieren',
    a11yToggleMute: 'Sprachausgabe stummschalten',
    a11yStartNewChat: 'Neuen Chat starten',
    a11yAddImage: 'Bild hinzufügen',
    a11yUploadImage: 'Bild zum Suchen hochladen',
    a11yOpenCamera: 'Kamera öffnen',
    a11yCameraDrawer: 'Kamera',
    a11yCameraPreview: 'Kameravorschau – richten Sie sie auf den zu suchenden Artikel',
    a11yCloseCamera: 'Kamera schließen',
    a11yTakePhoto: 'Foto aufnehmen',
    a11ySwitchCamera: 'Kamera wechseln',
    a11yCameraError: 'Kamera nicht verfügbar – überprüfen Sie die Berechtigungen oder wechseln Sie die Kamera',
    a11yStopVoiceInput: 'Aufnahme beenden und senden',
    holdMicToRecord: 'Mikrofon gedrückt halten, um aufzunehmen',
    voiceInputError: 'Spracheingabe nicht verfügbar',
    a11yChatInput: 'Geben Sie Ihre Nachricht an den Einkaufsassistenten ein',
    chatBoxPlaceholder: 'Nachricht eingeben',
    a11yTranscribingVoice: 'Sprachnachricht wird transkribiert',
    a11yListening: 'Hört zu',
    a11yHoldMicInstructions: 'Halten Sie gedrückt, oder halten Sie Leertaste oder Eingabetaste gedrückt, um aufzunehmen. Loslassen zum Senden.',
    a11ySendMessage: 'Nachricht senden',
  },
  it: {
    seeResults: 'Vedi risultati',
    noQueryProvided: 'Nessuna query di ricerca fornita.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} di sconto',
    addToCart: 'Aggiungi al carrello',
    gettingOverview: 'Sto pensando...',
    findingProducts: 'Ricerca dei prodotti...',
    aiOverviewLabel: 'Panoramica IA',
    a11yProductResultsShown: '{count} prodotti trovati',
    a11yAssistantThinking: 'L\'assistente sta pensando',
    a11yChatMessages: 'Messaggi dell\'assistente shopping',
    a11yScrollToLatestMessage: 'Scorri fino all\'ultimo messaggio',
    a11ySuggestedReplies: 'Risposte suggerite',
    a11yUploadedImage: 'Immagine caricata',
    nowDescribing: 'Descrizione in corso',
    showMore: 'Mostra altro...',
    a11yCloseFullScreen: 'Chiudi schermo intero',
    a11yEnableMute: 'Riattiva l\'uscita vocale',
    a11yToggleMute: 'Disattiva l\'uscita vocale',
    a11yStartNewChat: 'Avvia nuova chat',
    a11yAddImage: 'Aggiungi immagine',
    a11yUploadImage: 'Carica un\'immagine per cercare',
    a11yOpenCamera: 'Apri fotocamera',
    a11yCameraDrawer: 'Fotocamera',
    a11yCameraPreview: 'Anteprima della fotocamera: inquadra l\'articolo da cercare',
    a11yCloseCamera: 'Chiudi fotocamera',
    a11yTakePhoto: 'Scatta foto',
    a11ySwitchCamera: 'Cambia fotocamera',
    a11yCameraError: 'Fotocamera non disponibile: controlla le autorizzazioni o prova a cambiare fotocamera',
    a11yStopVoiceInput: 'Interrompi registrazione e invia',
    holdMicToRecord: 'Tieni premuto il microfono per registrare',
    voiceInputError: 'Input vocale non disponibile',
    a11yChatInput: 'Scrivi il tuo messaggio all\'assistente shopping',
    chatBoxPlaceholder: 'Scrivi il tuo messaggio',
    a11yTranscribingVoice: 'Trascrizione del messaggio vocale',
    a11yListening: 'Ascolto in corso',
    a11yHoldMicInstructions: 'Tieni premuto, oppure tieni premuto Spazio o Invio, per registrare. Rilascia per inviare.',
    a11ySendMessage: 'Invia messaggio',
  },
  pl: {
    seeResults: 'Zobacz wyniki',
    noQueryProvided: 'Nie podano zapytania wyszukiwania.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} zniżki',
    addToCart: 'Dodaj do koszyka',
    gettingOverview: 'Myślę...',
    findingProducts: 'Wyszukiwanie produktów...',
    aiOverviewLabel: 'Podsumowanie AI',
    a11yProductResultsShown: 'Znaleziono {count} produktów',
    a11yAssistantThinking: 'Asystent myśli',
    a11yChatMessages: 'Wiadomości asystenta zakupów',
    a11yScrollToLatestMessage: 'Przewiń do najnowszej wiadomości',
    a11ySuggestedReplies: 'Sugerowane odpowiedzi',
    a11yUploadedImage: 'Przesłany obraz',
    nowDescribing: 'Teraz opisywane',
    showMore: 'Pokaż więcej...',
    a11yCloseFullScreen: 'Zamknij pełny ekran',
    a11yEnableMute: 'Włącz dźwięk głosowy',
    a11yToggleMute: 'Wycisz dźwięk głosowy',
    a11yStartNewChat: 'Rozpocznij nowy czat',
    a11yAddImage: 'Dodaj obraz',
    a11yUploadImage: 'Prześlij obraz, aby wyszukać',
    a11yOpenCamera: 'Otwórz aparat',
    a11yCameraDrawer: 'Aparat',
    a11yCameraPreview: 'Podgląd kamery — skieruj ją na przedmiot, aby wyszukać',
    a11yCloseCamera: 'Zamknij aparat',
    a11yTakePhoto: 'Zrób zdjęcie',
    a11ySwitchCamera: 'Przełącz aparat',
    a11yCameraError: 'Aparat niedostępny – sprawdź uprawnienia lub spróbuj zmienić aparat',
    a11yStopVoiceInput: 'Zatrzymaj nagrywanie i wyślij',
    holdMicToRecord: 'Przytrzymaj mikrofon, aby nagrywać',
    voiceInputError: 'Wprowadzanie głosowe niedostępne',
    a11yChatInput: 'Wpisz wiadomość do asystenta zakupów',
    chatBoxPlaceholder: 'Wpisz wiadomość',
    a11yTranscribingVoice: 'Transkrybowanie wiadomości głosowej',
    a11yListening: 'Słucham',
    a11yHoldMicInstructions: 'Przytrzymaj lub przytrzymaj spację albo Enter, aby nagrywać. Zwolnij, aby wysłać.',
    a11ySendMessage: 'Wyślij wiadomość',
  },
  ko: {
    seeResults: '결과 보기',
    noQueryProvided: '검색어가 제공되지 않았습니다.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 할인',
    addToCart: '장바구니에 추가',
    gettingOverview: '생각 중...',
    findingProducts: '상품 찾는 중...',
    aiOverviewLabel: 'AI 요약',
    a11yProductResultsShown: '상품 {count}개 찾음',
    a11yAssistantThinking: '어시스턴트가 생각 중입니다',
    a11yChatMessages: '쇼핑 어시스턴트 메시지',
    a11yScrollToLatestMessage: '최신 메시지로 스크롤',
    a11ySuggestedReplies: '추천 답변',
    a11yUploadedImage: '업로드된 이미지',
    nowDescribing: '지금 설명 중',
    showMore: '더 보기...',
    a11yCloseFullScreen: '전체 화면 닫기',
    a11yEnableMute: '음성 출력 켜기',
    a11yToggleMute: '음성 출력 음소거',
    a11yStartNewChat: '새 채팅 시작',
    a11yAddImage: '이미지 추가',
    a11yUploadImage: '검색할 이미지 업로드',
    a11yOpenCamera: '카메라 열기',
    a11yCameraDrawer: '카메라',
    a11yCameraPreview: '카메라 미리보기 — 검색할 항목을 향하게 하세요',
    a11yCloseCamera: '카메라 닫기',
    a11yTakePhoto: '사진 찍기',
    a11ySwitchCamera: '카메라 전환',
    a11yCameraError: '카메라를 사용할 수 없습니다 — 권한을 확인하거나 카메라를 전환해 보세요',
    a11yStopVoiceInput: '녹음 중지 및 전송',
    holdMicToRecord: '마이크를 길게 눌러 녹음하세요',
    voiceInputError: '음성 입력을 사용할 수 없습니다',
    a11yChatInput: '쇼핑 어시스턴트에게 메시지를 입력하세요',
    chatBoxPlaceholder: '메시지를 입력하세요',
    a11yTranscribingVoice: '음성 메시지를 텍스트로 변환 중',
    a11yListening: '듣는 중',
    a11yHoldMicInstructions: '녹음하려면 길게 누르거나 스페이스바 또는 엔터 키를 길게 누르세요. 놓으면 전송됩니다.',
    a11ySendMessage: '메시지 보내기',
  },
  ja: {
    seeResults: '結果を見る',
    noQueryProvided: '検索クエリが指定されていません。',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 割引',
    addToCart: 'カートに追加',
    gettingOverview: '考え中...',
    findingProducts: '商品を検索中...',
    aiOverviewLabel: 'AI概要',
    a11yProductResultsShown: '{count}件の商品が見つかりました',
    a11yAssistantThinking: 'アシスタントが考え中です',
    a11yChatMessages: 'ショッピングアシスタントのメッセージ',
    a11yScrollToLatestMessage: '最新のメッセージまでスクロール',
    a11ySuggestedReplies: '返信の候補',
    a11yUploadedImage: 'アップロードされた画像',
    nowDescribing: '説明中',
    showMore: 'もっと見る...',
    a11yCloseFullScreen: 'フルスクリーンを閉じる',
    a11yEnableMute: '音声出力をオンにする',
    a11yToggleMute: '音声出力をミュート',
    a11yStartNewChat: '新しいチャットを開始',
    a11yAddImage: '画像を追加',
    a11yUploadImage: '検索する画像をアップロード',
    a11yOpenCamera: 'カメラを開く',
    a11yCameraDrawer: 'カメラ',
    a11yCameraPreview: 'カメラプレビュー — 検索する商品にカメラを向けてください',
    a11yCloseCamera: 'カメラを閉じる',
    a11yTakePhoto: '写真を撮る',
    a11ySwitchCamera: 'カメラを切り替える',
    a11yCameraError: 'カメラを利用できません — 権限を確認するか、カメラの切り替えをお試しください',
    a11yStopVoiceInput: '録音を停止して送信',
    holdMicToRecord: 'マイクを長押しして録音',
    voiceInputError: '音声入力は利用できません',
    a11yChatInput: 'ショッピングアシスタントにメッセージを入力',
    chatBoxPlaceholder: 'メッセージを入力',
    a11yTranscribingVoice: '音声メッセージを文字起こし中',
    a11yListening: '聞いています',
    a11yHoldMicInstructions: '録音するには長押しするか、スペースキーまたはEnterキーを長押ししてください。離すと送信されます。',
    a11ySendMessage: 'メッセージを送信',
  },
  th: {
    seeResults: 'ดูผลลัพธ์',
    noQueryProvided: 'ไม่มีการระบุคำค้นหา',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: 'ลดราคา {discount}',
    addToCart: 'เพิ่มสินค้าลงตะกร้า',
    gettingOverview: 'กำลังคิด...',
    findingProducts: 'กำลังค้นหาสินค้า...',
    aiOverviewLabel: 'ภาพรวมจาก AI',
    a11yProductResultsShown: 'พบสินค้า {count} รายการ',
    a11yAssistantThinking: 'ผู้ช่วยกำลังคิด',
    a11yChatMessages: 'ข้อความของผู้ช่วยช้อปปิ้ง',
    a11yScrollToLatestMessage: 'เลื่อนไปยังข้อความล่าสุด',
    a11ySuggestedReplies: 'คำตอบที่แนะนำ',
    a11yUploadedImage: 'รูปภาพที่อัปโหลด',
    nowDescribing: 'กำลังอธิบาย',
    showMore: 'แสดงเพิ่มเติม...',
    a11yCloseFullScreen: 'ปิดเต็มหน้าจอ',
    a11yEnableMute: 'เปิดเสียงพูด',
    a11yToggleMute: 'ปิดเสียงพูด',
    a11yStartNewChat: 'เริ่มแชทใหม่',
    a11yAddImage: 'เพิ่มรูปภาพ',
    a11yUploadImage: 'อัปโหลดรูปภาพเพื่อค้นหา',
    a11yOpenCamera: 'เปิดกล้อง',
    a11yCameraDrawer: 'กล้อง',
    a11yCameraPreview: 'ตัวอย่างกล้อง — เล็งไปที่สินค้าที่ต้องการค้นหา',
    a11yCloseCamera: 'ปิดกล้อง',
    a11yTakePhoto: 'ถ่ายรูป',
    a11ySwitchCamera: 'สลับกล้อง',
    a11yCameraError: 'ไม่สามารถใช้กล้องได้ — ตรวจสอบสิทธิ์การเข้าถึงหรือลองสลับกล้อง',
    a11yStopVoiceInput: 'หยุดบันทึกและส่ง',
    holdMicToRecord: 'กดค้างที่ไมโครโฟนเพื่อบันทึกเสียง',
    voiceInputError: 'ไม่สามารถใช้การป้อนด้วยเสียงได้',
    a11yChatInput: 'พิมพ์ข้อความถึงผู้ช่วยช้อปปิ้ง',
    chatBoxPlaceholder: 'พิมพ์ข้อความของคุณ',
    a11yTranscribingVoice: 'กำลังถอดเสียงข้อความเสียง',
    a11yListening: 'กำลังฟัง',
    a11yHoldMicInstructions: 'กดค้างไว้ หรือกดค้างที่ Space หรือ Enter เพื่อบันทึกเสียง ปล่อยเพื่อส่ง',
    a11ySendMessage: 'ส่งข้อความ',
  },
  zh: {
    seeResults: '查看结果',
    noQueryProvided: '未提供搜索查询。',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 折扣',
    addToCart: '加入购物车',
    gettingOverview: '正在思考...',
    findingProducts: '正在查找商品...',
    aiOverviewLabel: 'AI概览',
    a11yProductResultsShown: '找到 {count} 件商品',
    a11yAssistantThinking: '助手正在思考',
    a11yChatMessages: '购物助手消息',
    a11yScrollToLatestMessage: '滚动到最新消息',
    a11ySuggestedReplies: '建议回复',
    a11yUploadedImage: '已上传图片',
    nowDescribing: '正在描述',
    showMore: '显示更多...',
    a11yCloseFullScreen: '关闭全屏',
    a11yEnableMute: '取消静音语音输出',
    a11yToggleMute: '静音语音输出',
    a11yStartNewChat: '开始新对话',
    a11yAddImage: '添加图片',
    a11yUploadImage: '上传图片以搜索',
    a11yOpenCamera: '打开相机',
    a11yCameraDrawer: '相机',
    a11yCameraPreview: '相机预览 — 将镜头对准要搜索的商品',
    a11yCloseCamera: '关闭相机',
    a11yTakePhoto: '拍照',
    a11ySwitchCamera: '切换相机',
    a11yCameraError: '相机不可用 — 请检查权限或尝试切换相机',
    a11yStopVoiceInput: '停止录音并发送',
    holdMicToRecord: '按住麦克风进行录音',
    voiceInputError: '语音输入不可用',
    a11yChatInput: '向购物助手输入您的消息',
    chatBoxPlaceholder: '输入您的消息',
    a11yTranscribingVoice: '正在转录语音消息',
    a11yListening: '正在聆听',
    a11yHoldMicInstructions: '按住，或按住空格键或回车键进行录音。松开即可发送。',
    a11ySendMessage: '发送消息',
  },
};

export const DEFAULT_CUSTOMIZATIONS: WidgetConfig['customizations'] = {
  breakpoints: {
    mobile: {
      maxWidth: 767,
    },
    tablet: {
      maxWidth: 1023,
    },
  },
  productGrid: {
    mobile: {
      productsPerRow: 2,
      marginHorizontal: 8,
      marginVertical: 0,
    },
    tablet: {
      productsPerRow: 3,
      marginHorizontal: 8,
      marginVertical: 0,
    },
    desktop: {
      productsPerRow: 4,
      marginHorizontal: 8,
      marginVertical: 0,
    },
  },
  productCard: {
    // Matches ai-search-launcher's product card look exactly (aspect ratio, link behavior, and
    // price/originalPrice visibility + colors).
    imageAspectRatio: '3 / 4',
    openLinksInNewTab: false,
    price: {
      show: true,
      font: {
        mobile: { size: 12, weight: 400 },
        tablet: { size: 12, weight: 400 },
        desktop: { size: 14, weight: 400 },
      },
      fontColor: '#B91C1C',
      fontColorDark: '#EF4444',
    },
    originalPrice: {
      show: true,
      font: {
        mobile: { size: 12, weight: 400 },
        tablet: { size: 12, weight: 400 },
        desktop: { size: 14, weight: 400 },
      },
      fontColor: '#6B7280',
      fontColorDark: '#9CA3AF',
      position: 'AFTER',
      strikethrough: true,
    },
    discount: {
      show: false,
      font: {
        mobile: { size: 12, weight: 400 },
        tablet: { size: 12, weight: 400 },
        desktop: { size: 14, weight: 400 },
      },
      fontColor: '#EF4444',
      fontColorDark: '#EF4444',
      showPercentage: true,
      rounding: 1,
    },
    title: {
      show: true,
      fieldSource: 'title',
      font: {
        mobile: { size: 14, weight: 700 },
        tablet: { size: 14, weight: 700 },
        desktop: { size: 16, weight: 700 },
      },
    },
    secondaryTitle: {
      show: false,
      fieldSource: 'brand',
      font: {
        mobile: { size: 12, weight: 400 },
        tablet: { size: 12, weight: 400 },
        desktop: { size: 14, weight: 400 },
      },
    },
    images: {
      mainImage: 'main',
      hoverImage: 'additional',
      showAlternatives: false,
    },
    findSimilar: {
      enable: false,
      position: 'bottom_right',
      icon: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
    },
    addToWishlist: {
      enable: false,
      position: 'top_right',
      iconInactive: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
      iconActive: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
    },
    addToCart: {
      enable: false,
      color: '#FFFFFF',
      colorDark: '#000000',
      backgroundColor: '#000000',
      backgroundColorDark: '#FFFFFF',
      layout: 'ICON_TEXT',
    },
  },
  buttons: {
    // Drives the send button (via bg-buttonPrimary/text-buttonPrimary, set as CSS custom
    // properties in setCssVariables()). White background requires a dark fontColor for
    // send-button contrast — using black (light mode) / mid-gray (dark mode), matching
    // ai-search-launcher's own default for this exact field. TurnSection's pre-expansion loading
    // dots (read as `loadingDotColor` in embedded-shopping-assistant-chat.tsx) use fontColor, not
    // backgroundColor, specifically so they stay visible against ESA's own white light-mode page
    // background (generalLayout.backgroundColor) instead of blending into it.
    primary: {
      fontColor: '#000000',
      fontColorDark: '#616161',
      backgroundColor: '#FFFFFF',
      backgroundColorDark: '#FFFFFF',
    },
    // fontColor/fontColorDark drive the "See Results" button's text + border (border matches
    // text color — see embedded-shopping-assistant-chat.tsx's seeResultsButtonColor). Previously
    // unused anywhere in ESA, so these were #FFFFFF/#000000 — fine while unwired, but that would
    // make the button invisible against ESA's own white (light) / dark (dark) page background now
    // that it's actually applied. Matches the button's previous hardcoded
    // text-gray-700/dark:text-neutral-100 exactly, so the default look is unchanged.
    // backgroundColor/backgroundColorDark remain unused (reserved for the button's hover state,
    // not wired yet) — left at their prior values.
    secondary: {
      fontColor: '#374151',
      fontColorDark: '#F5F5F5',
      backgroundColor: '#000000',
      backgroundColorDark: '#FFFFFF',
    },
  },
  generalLayout: {
    headingFont: {
      mobile: { size: 20, weight: 400 },
      tablet: { size: 22, weight: 400 },
      desktop: { size: 24, weight: 400 },
    },
    bodyFont: {
      mobile: { size: 14, weight: 400 },
      tablet: { size: 14, weight: 400 },
      desktop: { size: 16, weight: 400 },
    },
    fontFamily: '',
    // fontColor doubles as the icon/accent color for the sparkle logo, mic, camera, and "+"
    // buttons, AND (via FullScreenChatContainer's own iconColor derivation) the post-expansion
    // header's title text color and its mute/new-chat/close icons. Black (light) / white (dark)
    // matches ai-search-launcher's own default for this exact field.
    fontColor: '#000000',
    fontColorDark: '#FFFFFF',
    backgroundColor: '#FFFFFF',
    // Matches Tailwind neutral-900, the previous hardcoded dark-mode background of ESA's own page
    // containers — this field was unused (unwired) before, so this value keeps the default look
    // unchanged now that it's actually applied. Mirrors the same fix ai-search-launcher made for
    // FullScreenChatContainer's dialog background.
    backgroundColorDark: '#171717',
    // Matches Tailwind gray-200/neutral-700, TopBar's previous hardcoded border colors — same
    // "unwired until now" situation as backgroundColorDark above.
    border: {
      width: 1,
      color: '#E5E7EB',
      colorDark: '#404040',
    },
    // showWidgetTitle is a required field on the shared generalLayout type (common/wigmix-core.ts)
    // but ESA itself no longer reads it — the homepage title it used to gate was removed once ESA
    // started always receiving a query prop and skipping straight to the results view.
    showWidgetTitle: true,
    showViSenzeLogo: false,
    darkModeDefault: false,
  },
  chatbot: {
    // Required for chat.speechOutputEnabled (use-voice.ts) to be true, which is what gates
    // FullScreenChatContainer's mute/voice-narration toggle (showVoiceToggle) — without this,
    // the toggle never appears regardless of the isMuted/onToggleMute wiring. voiceId/voiceModelId
    // are left unset deliberately, same as ai-search-launcher's own default: falls back to the
    // widget's built-in voice.
    voiceEnabled: true,
    // Narration starts muted — a user has to deliberately opt in via the mute button rather than
    // being narrated to immediately on their first reply.
    startMuted: true,
  },
};
