import type { WidgetConfig } from '../../common/wigmix-core';
import type { LanguagePack } from '../../common/locales/locale';

export const DEFAULT_TEXTS: LanguagePack = {
  en: {
    widgetTitle: 'Shopping Assistant',
    seeResults: 'See Results',
    exploreMore: 'Explore more',
    systemError: 'Something went wrong. Please try again later.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} off',
    addToCart: 'Add to Cart',
    searchPlaceholder: 'Search for a product...',
    askPlaceholder: 'Ask anything...',
    gettingOverview: 'Thinking...',
    findingProducts: 'Finding products...',
    noProductsFound: 'No matching products found.',
    searchButton: 'Search',
    imageSearchTurnLabel: 'Image search',
    aiOverviewLabel: 'AI Overview',
    a11yReadAloud: 'Read aloud',
    a11yStopReading: 'Stop reading',
    a11yLoading: 'Loading assistant response',
    a11yCloseModal: 'Close',
    a11yNextSteps: 'Next step options',
    a11yProductResults: 'Product results',
    a11yProductResultsShown: '{count} products found',
    a11yVoiceSearch: 'Voice search',
    a11yImageSearch: 'Image search',
    a11yAddImage: 'Add image',
    a11yUploadImage: 'Upload an image to search',
    a11yOpenCamera: 'Open camera',
    a11yCameraDrawer: 'Camera',
    a11yCameraPreview: 'Camera preview — point at the item to search',
    a11yCloseCamera: 'Close camera',
    a11yTakePhoto: 'Take photo',
    a11ySwitchCamera: 'Switch camera',
    a11yCameraError: 'Camera unavailable — check permissions or try switching cameras',
    a11yStartVoiceInput: 'Start voice input',
    a11yStopVoiceInput: 'Stop recording and send',
    holdMicToRecord: 'Hold the mic to record',
    voiceInputError: 'Voice input unavailable',
    a11ySend: 'Send',
    a11yChatInput: 'Type your message to the shopping assistant',
    chatBoxPlaceholder: 'Type your message',
    a11yVoicePending: 'Preparing to listen',
    a11yHoldMicInstructions: 'Press and hold, or press and hold Space or Enter, to record. Release to send.',
    a11ySendMessage: 'Send message',
  },
  es: {
    widgetTitle: 'Asistente de compras',
    seeResults: 'Ver resultados',
    exploreMore: 'Explorar más',
    systemError: 'Algo salió mal. Por favor, inténtelo más tarde.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de descuento',
    addToCart: 'Agregar al carrito',
    searchPlaceholder: 'Buscar un producto...',
    askPlaceholder: 'Pregunta lo que quieras...',
    gettingOverview: 'Pensando...',
    findingProducts: 'Buscando productos...',
    noProductsFound: 'No se encontraron productos coincidentes.',
    searchButton: 'Buscar',
    imageSearchTurnLabel: 'Búsqueda por imagen',
    aiOverviewLabel: 'Resumen de IA',
    a11yReadAloud: 'Leer en voz alta',
    a11yStopReading: 'Detener lectura',
    a11yLoading: 'Cargando respuesta del asistente',
    a11yCloseModal: 'Cerrar',
    a11yNextSteps: 'Opciones de siguiente paso',
    a11yProductResults: 'Resultados de productos',
    a11yProductResultsShown: '{count} productos encontrados',
    a11yVoiceSearch: 'Búsqueda por voz',
    a11yImageSearch: 'Búsqueda por imagen',
    a11yAddImage: 'Agregar imagen',
    a11yUploadImage: 'Subir una imagen para buscar',
    a11yOpenCamera: 'Abrir cámara',
    a11yCameraDrawer: 'Cámara',
    a11yCameraPreview: 'Vista previa de la cámara: apunta al artículo para buscar',
    a11yCloseCamera: 'Cerrar cámara',
    a11yTakePhoto: 'Tomar foto',
    a11ySwitchCamera: 'Cambiar cámara',
    a11yCameraError: 'Cámara no disponible: verifique los permisos o intente cambiar de cámara',
    a11yStartVoiceInput: 'Iniciar entrada de voz',
    a11yStopVoiceInput: 'Detener grabación y enviar',
    holdMicToRecord: 'Mantén presionado el micrófono para grabar',
    voiceInputError: 'Entrada de voz no disponible',
    a11ySend: 'Enviar',
    a11yChatInput: 'Escribe tu mensaje al asistente de compras',
    chatBoxPlaceholder: 'Escribe tu mensaje',
    a11yVoicePending: 'Preparando para escuchar',
    a11yHoldMicInstructions: 'Mantén presionado, o mantén presionada la barra espaciadora o Enter, para grabar. Suelta para enviar.',
    a11ySendMessage: 'Enviar mensaje',
  },
  fr: {
    widgetTitle: 'Assistant shopping',
    seeResults: 'Voir les résultats',
    exploreMore: 'Explorer plus',
    systemError: 'Une erreur est survenue. Veuillez réessayer plus tard.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de réduction',
    addToCart: 'Ajouter au panier',
    searchPlaceholder: 'Rechercher un produit...',
    askPlaceholder: 'Posez votre question...',
    gettingOverview: 'Réflexion en cours...',
    findingProducts: 'Recherche de produits...',
    noProductsFound: 'Aucun produit correspondant trouvé.',
    searchButton: 'Rechercher',
    imageSearchTurnLabel: 'Recherche par image',
    aiOverviewLabel: 'Aperçu IA',
    a11yReadAloud: 'Lire à voix haute',
    a11yStopReading: 'Arrêter la lecture',
    a11yLoading: 'Chargement de la réponse de l\'assistant',
    a11yCloseModal: 'Fermer',
    a11yNextSteps: 'Options d\'étape suivante',
    a11yProductResults: 'Résultats de produits',
    a11yProductResultsShown: '{count} produits trouvés',
    a11yVoiceSearch: 'Recherche vocale',
    a11yImageSearch: 'Recherche par image',
    a11yAddImage: 'Ajouter une image',
    a11yUploadImage: 'Téléverser une image pour rechercher',
    a11yOpenCamera: 'Ouvrir la caméra',
    a11yCameraDrawer: 'Caméra',
    a11yCameraPreview: 'Aperçu de la caméra — pointez vers l\'article à rechercher',
    a11yCloseCamera: 'Fermer la caméra',
    a11yTakePhoto: 'Prendre une photo',
    a11ySwitchCamera: 'Changer de caméra',
    a11yCameraError: 'Caméra indisponible : vérifiez les autorisations ou essayez de changer de caméra',
    a11yStartVoiceInput: 'Démarrer la saisie vocale',
    a11yStopVoiceInput: 'Arrêter l\'enregistrement et envoyer',
    holdMicToRecord: 'Maintenez le micro enfoncé pour enregistrer',
    voiceInputError: 'Saisie vocale indisponible',
    a11ySend: 'Envoyer',
    a11yChatInput: 'Écrivez votre message à l\'assistant shopping',
    chatBoxPlaceholder: 'Écrivez votre message',
    a11yVoicePending: 'Préparation à l\'écoute',
    a11yHoldMicInstructions: 'Appuyez et maintenez, ou appuyez et maintenez Espace ou Entrée, pour enregistrer. Relâchez pour envoyer.',
    a11ySendMessage: 'Envoyer le message',
  },
  pt: {
    widgetTitle: 'Assistente de compras',
    seeResults: 'Ver resultados',
    exploreMore: 'Explorar mais',
    systemError: 'Algo deu errado. Por favor, tente novamente mais tarde.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de desconto',
    addToCart: 'Adicionar ao carrinho',
    searchPlaceholder: 'Pesquisar um produto...',
    askPlaceholder: 'Pergunte qualquer coisa...',
    gettingOverview: 'Pensando...',
    findingProducts: 'Encontrando produtos...',
    noProductsFound: 'Nenhum produto correspondente encontrado.',
    searchButton: 'Pesquisar',
    imageSearchTurnLabel: 'Pesquisa por imagem',
    aiOverviewLabel: 'Visão geral de IA',
    a11yReadAloud: 'Ler em voz alta',
    a11yStopReading: 'Parar leitura',
    a11yLoading: 'Carregando resposta do assistente',
    a11yCloseModal: 'Fechar',
    a11yNextSteps: 'Opções de próximo passo',
    a11yProductResults: 'Resultados de produtos',
    a11yProductResultsShown: '{count} produtos encontrados',
    a11yVoiceSearch: 'Pesquisa por voz',
    a11yImageSearch: 'Pesquisa por imagem',
    a11yAddImage: 'Adicionar imagem',
    a11yUploadImage: 'Enviar uma imagem para pesquisar',
    a11yOpenCamera: 'Abrir câmera',
    a11yCameraDrawer: 'Câmera',
    a11yCameraPreview: 'Pré-visualização da câmera — aponte para o item para pesquisar',
    a11yCloseCamera: 'Fechar câmera',
    a11yTakePhoto: 'Tirar foto',
    a11ySwitchCamera: 'Alternar câmera',
    a11yCameraError: 'Câmera indisponível: verifique as permissões ou tente trocar de câmera',
    a11yStartVoiceInput: 'Iniciar entrada de voz',
    a11yStopVoiceInput: 'Parar gravação e enviar',
    holdMicToRecord: 'Mantenha o microfone pressionado para gravar',
    voiceInputError: 'Entrada de voz indisponível',
    a11ySend: 'Enviar',
    a11yChatInput: 'Digite sua mensagem para o assistente de compras',
    chatBoxPlaceholder: 'Digite sua mensagem',
    a11yVoicePending: 'Preparando para ouvir',
    a11yHoldMicInstructions: 'Pressione e segure, ou pressione e segure Espaço ou Enter, para gravar. Solte para enviar.',
    a11ySendMessage: 'Enviar mensagem',
  },
  de: {
    widgetTitle: 'Einkaufsassistent',
    seeResults: 'Ergebnisse anzeigen',
    exploreMore: 'Mehr entdecken',
    systemError: 'Etwas ist schief gelaufen. Bitte versuchen Sie es später erneut.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} Rabatt',
    addToCart: 'In den Warenkorb',
    searchPlaceholder: 'Nach einem Produkt suchen...',
    askPlaceholder: 'Stellen Sie eine Frage...',
    gettingOverview: 'Denke nach...',
    findingProducts: 'Produkte werden gesucht...',
    noProductsFound: 'Keine passenden Produkte gefunden.',
    searchButton: 'Suchen',
    imageSearchTurnLabel: 'Bildsuche',
    aiOverviewLabel: 'KI-Übersicht',
    a11yReadAloud: 'Vorlesen',
    a11yStopReading: 'Vorlesen stoppen',
    a11yLoading: 'Antwort des Assistenten wird geladen',
    a11yCloseModal: 'Schließen',
    a11yNextSteps: 'Nächste Schritte',
    a11yProductResults: 'Produktergebnisse',
    a11yProductResultsShown: '{count} Produkte gefunden',
    a11yVoiceSearch: 'Sprachsuche',
    a11yImageSearch: 'Bildsuche',
    a11yAddImage: 'Bild hinzufügen',
    a11yUploadImage: 'Bild zum Suchen hochladen',
    a11yOpenCamera: 'Kamera öffnen',
    a11yCameraDrawer: 'Kamera',
    a11yCameraPreview: 'Kameravorschau – richten Sie sie auf den zu suchenden Artikel',
    a11yCloseCamera: 'Kamera schließen',
    a11yTakePhoto: 'Foto aufnehmen',
    a11ySwitchCamera: 'Kamera wechseln',
    a11yCameraError: 'Kamera nicht verfügbar – überprüfen Sie die Berechtigungen oder wechseln Sie die Kamera',
    a11yStartVoiceInput: 'Spracheingabe starten',
    a11yStopVoiceInput: 'Aufnahme beenden und senden',
    holdMicToRecord: 'Mikrofon gedrückt halten, um aufzunehmen',
    voiceInputError: 'Spracheingabe nicht verfügbar',
    a11ySend: 'Senden',
    a11yChatInput: 'Geben Sie Ihre Nachricht an den Einkaufsassistenten ein',
    chatBoxPlaceholder: 'Nachricht eingeben',
    a11yVoicePending: 'Bereitet sich vor zuzuhören',
    a11yHoldMicInstructions: 'Halten Sie gedrückt, oder halten Sie Leertaste oder Eingabetaste gedrückt, um aufzunehmen. Loslassen zum Senden.',
    a11ySendMessage: 'Nachricht senden',
  },
  it: {
    widgetTitle: 'Assistente shopping',
    seeResults: 'Vedi risultati',
    exploreMore: 'Esplora altro',
    systemError: 'Si è verificato un errore. Riprova più tardi.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} di sconto',
    addToCart: 'Aggiungi al carrello',
    searchPlaceholder: 'Cerca un prodotto...',
    askPlaceholder: 'Chiedi qualsiasi cosa...',
    gettingOverview: 'Sto pensando...',
    findingProducts: 'Ricerca dei prodotti...',
    noProductsFound: 'Nessun prodotto corrispondente trovato.',
    searchButton: 'Cerca',
    imageSearchTurnLabel: 'Ricerca per immagine',
    aiOverviewLabel: 'Panoramica IA',
    a11yReadAloud: 'Leggi ad alta voce',
    a11yStopReading: 'Interrompi lettura',
    a11yLoading: 'Caricamento risposta assistente',
    a11yCloseModal: 'Chiudi',
    a11yNextSteps: 'Opzioni passo successivo',
    a11yProductResults: 'Risultati prodotti',
    a11yProductResultsShown: '{count} prodotti trovati',
    a11yVoiceSearch: 'Ricerca vocale',
    a11yImageSearch: 'Ricerca per immagine',
    a11yAddImage: 'Aggiungi immagine',
    a11yUploadImage: 'Carica un\'immagine per cercare',
    a11yOpenCamera: 'Apri fotocamera',
    a11yCameraDrawer: 'Fotocamera',
    a11yCameraPreview: 'Anteprima della fotocamera: inquadra l\'articolo da cercare',
    a11yCloseCamera: 'Chiudi fotocamera',
    a11yTakePhoto: 'Scatta foto',
    a11ySwitchCamera: 'Cambia fotocamera',
    a11yCameraError: 'Fotocamera non disponibile: controlla le autorizzazioni o prova a cambiare fotocamera',
    a11yStartVoiceInput: 'Avvia input vocale',
    a11yStopVoiceInput: 'Interrompi registrazione e invia',
    holdMicToRecord: 'Tieni premuto il microfono per registrare',
    voiceInputError: 'Input vocale non disponibile',
    a11ySend: 'Invia',
    a11yChatInput: 'Scrivi il tuo messaggio all\'assistente shopping',
    chatBoxPlaceholder: 'Scrivi il tuo messaggio',
    a11yVoicePending: 'Preparazione all\'ascolto',
    a11yHoldMicInstructions: 'Tieni premuto, oppure tieni premuto Spazio o Invio, per registrare. Rilascia per inviare.',
    a11ySendMessage: 'Invia messaggio',
  },
  pl: {
    widgetTitle: 'Asystent zakupów',
    seeResults: 'Zobacz wyniki',
    exploreMore: 'Odkryj więcej',
    systemError: 'Wystąpił błąd. Spróbuj ponownie później.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} zniżki',
    addToCart: 'Dodaj do koszyka',
    searchPlaceholder: 'Szukaj produktu...',
    askPlaceholder: 'Zapytaj o cokolwiek...',
    gettingOverview: 'Myślę...',
    findingProducts: 'Wyszukiwanie produktów...',
    noProductsFound: 'Nie znaleziono pasujących produktów.',
    searchButton: 'Szukaj',
    imageSearchTurnLabel: 'Wyszukiwanie obrazem',
    aiOverviewLabel: 'Podsumowanie AI',
    a11yReadAloud: 'Czytaj na głos',
    a11yStopReading: 'Zatrzymaj czytanie',
    a11yLoading: 'Ładowanie odpowiedzi asystenta',
    a11yCloseModal: 'Zamknij',
    a11yNextSteps: 'Opcje następnego kroku',
    a11yProductResults: 'Wyniki produktów',
    a11yProductResultsShown: 'Znaleziono {count} produktów',
    a11yVoiceSearch: 'Wyszukiwanie głosowe',
    a11yImageSearch: 'Wyszukiwanie obrazem',
    a11yAddImage: 'Dodaj obraz',
    a11yUploadImage: 'Prześlij obraz, aby wyszukać',
    a11yOpenCamera: 'Otwórz aparat',
    a11yCameraDrawer: 'Aparat',
    a11yCameraPreview: 'Podgląd kamery — skieruj ją na przedmiot, aby wyszukać',
    a11yCloseCamera: 'Zamknij aparat',
    a11yTakePhoto: 'Zrób zdjęcie',
    a11ySwitchCamera: 'Przełącz aparat',
    a11yCameraError: 'Aparat niedostępny – sprawdź uprawnienia lub spróbuj zmienić aparat',
    a11yStartVoiceInput: 'Rozpocznij wprowadzanie głosowe',
    a11yStopVoiceInput: 'Zatrzymaj nagrywanie i wyślij',
    holdMicToRecord: 'Przytrzymaj mikrofon, aby nagrywać',
    voiceInputError: 'Wprowadzanie głosowe niedostępne',
    a11ySend: 'Wyślij',
    a11yChatInput: 'Wpisz wiadomość do asystenta zakupów',
    chatBoxPlaceholder: 'Wpisz wiadomość',
    a11yVoicePending: 'Przygotowywanie do słuchania',
    a11yHoldMicInstructions: 'Przytrzymaj lub przytrzymaj spację albo Enter, aby nagrywać. Zwolnij, aby wysłać.',
    a11ySendMessage: 'Wyślij wiadomość',
  },
  ko: {
    widgetTitle: '쇼핑 어시스턴트',
    seeResults: '결과 보기',
    exploreMore: '더 탐색하기',
    systemError: '오류가 발생했습니다. 나중에 다시 시도해주세요.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 할인',
    addToCart: '장바구니에 추가',
    searchPlaceholder: '상품 검색...',
    askPlaceholder: '무엇이든 물어보세요...',
    gettingOverview: '생각 중...',
    findingProducts: '상품 찾는 중...',
    noProductsFound: '일치하는 상품을 찾지 못했습니다.',
    searchButton: '검색',
    imageSearchTurnLabel: '이미지 검색',
    aiOverviewLabel: 'AI 요약',
    a11yReadAloud: '소리 내어 읽기',
    a11yStopReading: '읽기 중지',
    a11yLoading: '어시스턴트 응답 로드 중',
    a11yCloseModal: '닫기',
    a11yNextSteps: '다음 단계 옵션',
    a11yProductResults: '상품 결과',
    a11yProductResultsShown: '상품 {count}개 찾음',
    a11yVoiceSearch: '음성 검색',
    a11yImageSearch: '이미지 검색',
    a11yAddImage: '이미지 추가',
    a11yUploadImage: '검색할 이미지 업로드',
    a11yOpenCamera: '카메라 열기',
    a11yCameraDrawer: '카메라',
    a11yCameraPreview: '카메라 미리보기 — 검색할 항목을 향하게 하세요',
    a11yCloseCamera: '카메라 닫기',
    a11yTakePhoto: '사진 찍기',
    a11ySwitchCamera: '카메라 전환',
    a11yCameraError: '카메라를 사용할 수 없습니다 — 권한을 확인하거나 카메라를 전환해 보세요',
    a11yStartVoiceInput: '음성 입력 시작',
    a11yStopVoiceInput: '녹음 중지 및 전송',
    holdMicToRecord: '마이크를 길게 눌러 녹음하세요',
    voiceInputError: '음성 입력을 사용할 수 없습니다',
    a11ySend: '보내기',
    a11yChatInput: '쇼핑 어시스턴트에게 메시지를 입력하세요',
    chatBoxPlaceholder: '메시지를 입력하세요',
    a11yVoicePending: '들을 준비 중',
    a11yHoldMicInstructions: '녹음하려면 길게 누르거나 스페이스바 또는 엔터 키를 길게 누르세요. 놓으면 전송됩니다.',
    a11ySendMessage: '메시지 보내기',
  },
  ja: {
    widgetTitle: 'ショッピングアシスタント',
    seeResults: '結果を見る',
    exploreMore: 'さらに探す',
    systemError: 'システムエラーが発生しました。後で再試してください。',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 割引',
    addToCart: 'カートに追加',
    searchPlaceholder: '商品を検索...',
    askPlaceholder: '何でも聞いてください...',
    gettingOverview: '考え中...',
    findingProducts: '商品を検索中...',
    noProductsFound: '一致する商品が見つかりませんでした。',
    searchButton: '検索',
    imageSearchTurnLabel: '画像検索',
    aiOverviewLabel: 'AI概要',
    a11yReadAloud: '読み上げ',
    a11yStopReading: '読み上げを停止',
    a11yLoading: 'アシスタントの回答を読み込み中',
    a11yCloseModal: '閉じる',
    a11yNextSteps: '次のステップの選択肢',
    a11yProductResults: '商品結果',
    a11yProductResultsShown: '{count}件の商品が見つかりました',
    a11yVoiceSearch: '音声検索',
    a11yImageSearch: '画像検索',
    a11yAddImage: '画像を追加',
    a11yUploadImage: '検索する画像をアップロード',
    a11yOpenCamera: 'カメラを開く',
    a11yCameraDrawer: 'カメラ',
    a11yCameraPreview: 'カメラプレビュー — 検索する商品にカメラを向けてください',
    a11yCloseCamera: 'カメラを閉じる',
    a11yTakePhoto: '写真を撮る',
    a11ySwitchCamera: 'カメラを切り替える',
    a11yCameraError: 'カメラを利用できません — 権限を確認するか、カメラの切り替えをお試しください',
    a11yStartVoiceInput: '音声入力を開始',
    a11yStopVoiceInput: '録音を停止して送信',
    holdMicToRecord: 'マイクを長押しして録音',
    voiceInputError: '音声入力は利用できません',
    a11ySend: '送信',
    a11yChatInput: 'ショッピングアシスタントにメッセージを入力',
    chatBoxPlaceholder: 'メッセージを入力',
    a11yVoicePending: '聞く準備をしています',
    a11yHoldMicInstructions: '録音するには長押しするか、スペースキーまたはEnterキーを長押ししてください。離すと送信されます。',
    a11ySendMessage: 'メッセージを送信',
  },
  th: {
    widgetTitle: 'ผู้ช่วยช้อปปิ้ง',
    seeResults: 'ดูผลลัพธ์',
    exploreMore: 'สำรวจเพิ่มเติม',
    systemError: 'เกิดข้อผิดพลาด กรุณาลองอีกครั้ง',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: 'ลดราคา {discount}',
    addToCart: 'เพิ่มสินค้าลงตะกร้า',
    searchPlaceholder: 'ค้นหาสินค้า...',
    askPlaceholder: 'ถามอะไรก็ได้...',
    gettingOverview: 'กำลังคิด...',
    findingProducts: 'กำลังค้นหาสินค้า...',
    noProductsFound: 'ไม่พบสินค้าที่ตรงกัน',
    searchButton: 'ค้นหา',
    imageSearchTurnLabel: 'ค้นหาด้วยรูปภาพ',
    aiOverviewLabel: 'ภาพรวมจาก AI',
    a11yReadAloud: 'อ่านออกเสียง',
    a11yStopReading: 'หยุดอ่าน',
    a11yLoading: 'กำลังโหลดคำตอบของผู้ช่วย',
    a11yCloseModal: 'ปิด',
    a11yNextSteps: 'ตัวเลือกขั้นตอนถัดไป',
    a11yProductResults: 'ผลลัพธ์สินค้า',
    a11yProductResultsShown: 'พบสินค้า {count} รายการ',
    a11yVoiceSearch: 'ค้นหาด้วยเสียง',
    a11yImageSearch: 'ค้นหาด้วยรูปภาพ',
    a11yAddImage: 'เพิ่มรูปภาพ',
    a11yUploadImage: 'อัปโหลดรูปภาพเพื่อค้นหา',
    a11yOpenCamera: 'เปิดกล้อง',
    a11yCameraDrawer: 'กล้อง',
    a11yCameraPreview: 'ตัวอย่างกล้อง — เล็งไปที่สินค้าที่ต้องการค้นหา',
    a11yCloseCamera: 'ปิดกล้อง',
    a11yTakePhoto: 'ถ่ายรูป',
    a11ySwitchCamera: 'สลับกล้อง',
    a11yCameraError: 'ไม่สามารถใช้กล้องได้ — ตรวจสอบสิทธิ์การเข้าถึงหรือลองสลับกล้อง',
    a11yStartVoiceInput: 'เริ่มป้อนข้อมูลด้วยเสียง',
    a11yStopVoiceInput: 'หยุดบันทึกและส่ง',
    holdMicToRecord: 'กดค้างที่ไมโครโฟนเพื่อบันทึกเสียง',
    voiceInputError: 'ไม่สามารถใช้การป้อนด้วยเสียงได้',
    a11ySend: 'ส่ง',
    a11yChatInput: 'พิมพ์ข้อความถึงผู้ช่วยช้อปปิ้ง',
    chatBoxPlaceholder: 'พิมพ์ข้อความของคุณ',
    a11yVoicePending: 'กำลังเตรียมพร้อมรับฟัง',
    a11yHoldMicInstructions: 'กดค้างไว้ หรือกดค้างที่ Space หรือ Enter เพื่อบันทึกเสียง ปล่อยเพื่อส่ง',
    a11ySendMessage: 'ส่งข้อความ',
  },
  zh: {
    widgetTitle: '购物助手',
    seeResults: '查看结果',
    exploreMore: '探索更多',
    systemError: '抱歉，系统暂时遇到问题，请稍后再试。',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 折扣',
    addToCart: '加入购物车',
    searchPlaceholder: '搜索商品...',
    askPlaceholder: '随便问点什么...',
    gettingOverview: '正在思考...',
    findingProducts: '正在查找商品...',
    noProductsFound: '未找到匹配的商品。',
    searchButton: '搜索',
    imageSearchTurnLabel: '图片搜索',
    aiOverviewLabel: 'AI概览',
    a11yReadAloud: '朗读',
    a11yStopReading: '停止朗读',
    a11yLoading: '正在加载助手回复',
    a11yCloseModal: '关闭',
    a11yNextSteps: '下一步选项',
    a11yProductResults: '商品结果',
    a11yProductResultsShown: '找到 {count} 件商品',
    a11yVoiceSearch: '语音搜索',
    a11yImageSearch: '图片搜索',
    a11yAddImage: '添加图片',
    a11yUploadImage: '上传图片以搜索',
    a11yOpenCamera: '打开相机',
    a11yCameraDrawer: '相机',
    a11yCameraPreview: '相机预览 — 将镜头对准要搜索的商品',
    a11yCloseCamera: '关闭相机',
    a11yTakePhoto: '拍照',
    a11ySwitchCamera: '切换相机',
    a11yCameraError: '相机不可用 — 请检查权限或尝试切换相机',
    a11yStartVoiceInput: '开始语音输入',
    a11yStopVoiceInput: '停止录音并发送',
    holdMicToRecord: '按住麦克风进行录音',
    voiceInputError: '语音输入不可用',
    a11ySend: '发送',
    a11yChatInput: '向购物助手输入您的消息',
    chatBoxPlaceholder: '输入您的消息',
    a11yVoicePending: '正在准备聆听',
    a11yHoldMicInstructions: '按住，或按住空格键或回车键进行录音。松开即可发送。',
    a11ySendMessage: '发送消息',
  },
};

export const DEFAULT_CUSTOMIZATIONS: WidgetConfig['customizations'] = {
  breakpoints: {
    mobile: {
      maxWidth: 767,
    },
    tablet: {
      maxWidth: 1023,
    },
  },
  productGrid: {
    mobile: {
      productsPerRow: 2,
      marginHorizontal: 8,
      marginVertical: 0,
    },
    tablet: {
      productsPerRow: 3,
      marginHorizontal: 8,
      marginVertical: 0,
    },
    desktop: {
      productsPerRow: 4,
      marginHorizontal: 8,
      marginVertical: 0,
    },
  },
  productCard: {
    imageAspectRatio: '2 / 3',
    // Opens in a new tab by default, preserving this widget's existing behavior (the host page stays
    // on the search results). Configurable like every other field here.
    openLinksInNewTab: true,
    // Price/secondary-title are OFF by default (this widget's cards intentionally show image + title
    // only), but are now genuinely configurable — a host can flip `show: true` to bring them back.
    price: {
      show: false,
      font: {
        mobile: { size: 12, weight: 400 },
        tablet: { size: 12, weight: 400 },
        desktop: { size: 14, weight: 400 },
      },
      fontColor: '#EF4444',
      fontColorDark: '#EF4444',
    },
    originalPrice: {
      show: false,
      font: {
        mobile: { size: 12, weight: 400 },
        tablet: { size: 12, weight: 400 },
        desktop: { size: 14, weight: 400 },
      },
      fontColor: '#9CA3AF',
      fontColorDark: '#9CA3AF',
      position: 'AFTER',
      strikethrough: true,
    },
    discount: {
      show: false,
      font: {
        mobile: { size: 12, weight: 400 },
        tablet: { size: 12, weight: 400 },
        desktop: { size: 14, weight: 400 },
      },
      fontColor: '#EF4444',
      fontColorDark: '#EF4444',
      showPercentage: true,
      rounding: 1,
    },
    title: {
      show: true,
      fieldSource: 'title',
      font: {
        mobile: { size: 14, weight: 700 },
        tablet: { size: 14, weight: 700 },
        desktop: { size: 16, weight: 700 },
      },
    },
    secondaryTitle: {
      show: false,
      fieldSource: 'brand',
      font: {
        mobile: { size: 12, weight: 400 },
        tablet: { size: 12, weight: 400 },
        desktop: { size: 14, weight: 400 },
      },
    },
    images: {
      mainImage: 'main',
      hoverImage: 'additional',
      showAlternatives: false,
    },
    findSimilar: {
      enable: false,
      position: 'bottom_right',
      icon: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
    },
    addToWishlist: {
      enable: false,
      position: 'top_right',
      iconInactive: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
      iconActive: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
    },
    addToCart: {
      enable: false,
      color: '#FFFFFF',
      colorDark: '#000000',
      backgroundColor: '#000000',
      backgroundColorDark: '#FFFFFF',
      layout: 'ICON_TEXT',
    },
  },
  buttons: {
    // Drives the send button and other primary-CTA-style elements (loading dots, selected chip).
    // Defaults to the widget's Google-blue accent; override to rebrand.
    primary: {
      fontColor: '#FFFFFF',
      fontColorDark: '#FFFFFF',
      backgroundColor: '#4285f4',
      backgroundColorDark: '#4285f4',
    },
    secondary: {
      fontColor: '#FFFFFF',
      fontColorDark: '#000000',
      backgroundColor: '#000000',
      backgroundColorDark: '#FFFFFF',
    },
  },
  generalLayout: {
    headingFont: {
      mobile: { size: 20, weight: 400 },
      tablet: { size: 22, weight: 400 },
      desktop: { size: 24, weight: 400 },
    },
    bodyFont: {
      mobile: { size: 14, weight: 400 },
      tablet: { size: 14, weight: 400 },
      desktop: { size: 16, weight: 400 },
    },
    fontFamily: '',
    // fontColor doubles as the icon/accent color for the sparkle logo, mic, camera, and "+" buttons.
    fontColor: '#4285f4',
    fontColorDark: '#4285f4',
    backgroundColor: '#FFFFFF',
    backgroundColorDark: '#000000',
    showWidgetTitle: true,
    showViSenzeLogo: false,
    darkModeDefault: false,
  },
};
