import type { WidgetConfig } from '../../common/wigmix-core';
import type { LanguagePack } from '../../common/locales/locale';

export const DEFAULT_TEXTS: LanguagePack = {
  en: {
    widgetTitle: 'Alternate Picks',
    widgetDescription: 'Or type your own recommendation query below',
    searchBarButton: 'Show Me',
    searchBarPlaceholder: 'an outfit to go with this',
    similarItemsTabButton: 'Similar Items',
    outfitRecommendationsTabButton: 'Outfit Recommendations',
    resultLoading1: 'Searching the latest trends...',
    resultLoading2: 'Finding the perfect look...',
    resultLoading3: 'Almost there...',
    resultRendering: 'Here\'s what I found for you',
    resultCarouselTitle: 'Results for',
    systemError: 'Something went wrong. Please try again later.',
    imageOrQueryNotFound: 'The image or query was not found. Please try again later.',
  },
  es: {
    widgetTitle: 'Personaliza tus recomendaciones',
    searchBarButton: 'Recomiéndame',
    searchBarPlaceholder: 'un conjunto para combinar con esto',
    similarItemsTabButton: 'Artículos Similares',
    outfitRecommendationsTabButton: 'Recomendaciones para Outfits',
    resultLoading1: 'Buscando las últimas tendencias...',
    resultLoading2: 'Encontrando el look perfecto...',
    resultLoading3: 'Casi listo...',
    resultRendering: 'Esto es lo que encontré para ti',
    resultCarouselTitle: 'Resultados para',
    systemError: 'Algo salió mal. Por favor, inténtelo más tarde.',
    imageOrQueryNotFound: 'La imagen o la consulta no se encontraron. Por favor, inténtelo más tarde.',
  },
  fr: {
    widgetTitle: 'Personnalisez vos recommandations',
    searchBarButton: 'Recommandez-moi',
    searchBarPlaceholder: 'une tenue pour aller avec ça',
    similarItemsTabButton: 'Articles Similaires',
    outfitRecommendationsTabButton: 'Recommandations pour Outfits',
    resultLoading1: 'Recherche des dernières tendances...',
    resultLoading2: 'Trouver le look parfait...',
    resultLoading3: 'Presque là...',
    resultRendering: 'Voici ce que j\'ai trouvé pour vous',
    resultCarouselTitle: 'Résultats pour',
    systemError: 'Une erreur est survenue. Veuillez réessayer plus tard.',
    imageOrQueryNotFound: 'L\'image ou la requête n\'a pas été trouvée. Veuillez réessayer plus tard.',
  },
  pt: {
    widgetTitle: 'Personalize suas recomendações',
    searchBarButton: 'Recomende-me',
    searchBarPlaceholder: 'uma roupa para combinar com isto',
    similarItemsTabButton: 'Artigos Semelhantes',
    outfitRecommendationsTabButton: 'Recomendações de Roupas',
    resultLoading1: 'Buscando as últimas tendências...',
    resultLoading2: 'Encontrando o look perfeito...',
    resultLoading3: 'Quase lá...',
    resultRendering: 'Isto é o que encontrei para você',
    resultCarouselTitle: 'Resultados para',
    systemError: 'Algo deu errado. Por favor, tente novamente mais tarde.',
    imageOrQueryNotFound: 'A imagem ou a consulta não foi encontrada. Por favor, tente novamente mais tarde.',
  },
  de: {
    widgetTitle: 'Personalisiere deine Empfehlungen',
    searchBarButton: 'Empfiehl mir',
    searchBarPlaceholder: 'ein Outfit passend dazu',
    similarItemsTabButton: 'Ähnliche Artikel',
    outfitRecommendationsTabButton: 'Empfehlungen für Outfits',
    resultLoading1: 'Suche nach den neuesten Trends...',
    resultLoading2: 'Finde den perfekten Look...',
    resultLoading3: 'Fast fertig...',
    resultRendering: 'Das habe ich für dich gefunden',
    resultCarouselTitle: 'Ergebnisse für',
    systemError: 'Etwas ist schief gelaufen. Bitte versuchen Sie es später erneut.',
    imageOrQueryNotFound: 'Die Bild oder die Abfrage wurde nicht gefunden. Bitte versuchen Sie es später erneut.',
  },
  it: {
    widgetTitle: 'Personalizza i tuoi suggerimenti',
    searchBarButton: 'Consigliami',
    searchBarPlaceholder: 'un outfit da abbinare a questo',
    similarItemsTabButton: 'Articoli Simili',
    outfitRecommendationsTabButton: 'Consigli per Outfit',
    resultLoading1: 'Ricerca delle ultime tendenze...',
    resultLoading2: 'Trovare il look perfetto...',
    resultLoading3: 'Quasi pronto...',
    resultRendering: 'Ecco cosa ho trovato per te',
    resultCarouselTitle: 'Risultati per',
    systemError: 'Si è verificato un errore. Riprova più tardi.',
    imageOrQueryNotFound: 'L\'immagine o la query non sono state trovate. Riprova più tardi.',
  },
  pl: {
    widgetTitle: 'Spersonalizuj swoje rekomendacje',
    searchBarButton: 'Zarekomenduj mi',
    searchBarPlaceholder: 'stylizacja pasująca do tego',
    similarItemsTabButton: 'Artikli Podobne',
    outfitRecommendationsTabButton: 'Rekomendacje dla Outfitów',
    resultLoading1: 'Wyszukiwanie najnowszych trendów...',
    resultLoading2: 'Szukam idealnego wyglądu...',
    resultLoading3: 'Już prawie gotowe...',
    resultRendering: 'Oto, co dla Ciebie znalazłem',
    resultCarouselTitle: 'Wyniki dla',
    systemError: 'Wystąpił błąd. Spróbuj ponownie później.',
    imageOrQueryNotFound: 'Obraz lub zapytanie nie zostały znalezione. Spróbuj ponownie później.',
  },
  ko: {
    widgetTitle: '추천 맞춤 설정',
    searchBarButton: '추천해 주세요',
    searchBarPlaceholder: '이 상품에 어울리는 의상',
    similarItemsTabButton: '유사 상품',
    outfitRecommendationsTabButton: '추천 상품',
    resultLoading1: '최신 트렌드 검색 중...',
    resultLoading2: '완벽한 스타일 찾는 중...',
    resultLoading3: '거의 다 왔어요...',
    resultRendering: '찾은 결과입니다',
    resultCarouselTitle: '검색 결과',
    systemError: '오류가 발생했습니다. 나중에 다시 시도해주세요.',
    imageOrQueryNotFound: '이미지 또는 쿼리가 찾을 수 없습니다. 나중에 다시 시도해주세요.',
  },
  ja: {
    widgetTitle: 'おすすめをパーソナライズ',
    searchBarButton: 'おすすめ',
    searchBarPlaceholder: 'これに合う服装',
    similarItemsTabButton: '類似商品',
    outfitRecommendationsTabButton: 'おすすめ商品',
    resultLoading1: '最新トレンドを検索中...',
    resultLoading2: '完璧なルックを検索中...',
    resultLoading3: 'まもなく完了...',
    resultRendering: 'あなたへのおすすめはこちらです',
    resultCarouselTitle: '検索結果',
    systemError: 'システムエラーが発生しました。後で再試してください。',
    imageOrQueryNotFound: '画像またはクエリが見つかりませんでした。後で再試してください。',
  },
  th: {
    widgetTitle: 'ปรับแต่งคำแนะนำของคุณ',
    searchBarButton: 'แนะนำฉัน',
    searchBarPlaceholder: 'ชุดที่จะเข้ากับสิ่งนี้',
    similarItemsTabButton: 'สินค้าที่คล้ายกัน',
    outfitRecommendationsTabButton: 'แนะนำชุด',
    resultLoading1: 'กำลังค้นหาเทรนด์ล่าสุด...',
    resultLoading2: 'กำลังค้นหาสไตล์ที่สมบูรณ์แบบ...',
    resultLoading3: 'อีกไม่นาน...',
    resultRendering: 'นี่คือสิ่งที่ฉันพบสำหรับคุณ',
    resultCarouselTitle: 'ผลลัพธ์สำหรับ',
    systemError: 'เกิดข้อผิดพลาด กรุณาลองอีกครั้ง',
    imageOrQueryNotFound: 'ไม่พบภาพหรือคำค้น กรุณาลองอีกครั้ง',
  },
};

export const DEFAULT_CUSTOMIZATIONS: WidgetConfig['customizations'] = {
  breakpoints: {
    mobile: {
      maxWidth: 767,
    },
    tablet: {
      maxWidth: 1023,
    },
  },
  productGrid: {
    mobile: {
      productsPerRow: 2,
      marginHorizontal: 16,
      marginVertical: 0,
    },
    tablet: {
      productsPerRow: 3,
      marginHorizontal: 8,
      marginVertical: 0,
    },
    desktop: {
      productsPerRow: 3,
      marginHorizontal: 8,
      marginVertical: 0,
    },
  },
  productCard: {
    imageAspectRatio: '2 / 3',
    openLinksInNewTab: false,
    price: {
      show: true,
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
      fontColor: '#EF4444',
      fontColorDark: '#EF4444',
    },
    originalPrice: {
      show: true,
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
      fontColor: '#9CA3AF',
      fontColorDark: '#9CA3AF',
    },
    title: {
      show: false,
      fieldSource: 'title',
      font: {
        mobile: {
          size: 14,
          weight: 700,
        },
        tablet: {
          size: 14,
          weight: 700,
        },
        desktop: {
          size: 16,
          weight: 700,
        },
      },
    },
    secondaryTitle: {
      show: true,
      fieldSource: 'brand',
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
    },
    images: {
      mainImage: 'main',
      hoverImage: 'additional',
      showAlternatives: false,
    },
    findSimilar: {
      enable: false,
      position: 'bottom_right',
      icon: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
    },
    addToWishlist: {
      enable: false,
      position: 'top_right',
      iconInactive: {
        color: '#FFFFFF',
        colorDark: '#FFFFFF',
        backgroundColor: '#616161',
        backgroundColorDark: '#616161',
      },
      iconActive: {
        color: '#FFFFFF',
        colorDark: '#FFFFFF',
        backgroundColor: '#616161',
        backgroundColorDark: '#616161',
      },
    },
  },
  buttons: {
    primary: {
      fontColor: '#FFFFFF',
      fontColorDark: '#616161',
      backgroundColor: '#616161',
      backgroundColorDark: '#FFFFFF',
    },
    secondary: {
      fontColor: '#FFFFFF',
      fontColorDark: '#000000',
      backgroundColor: '#000000',
      backgroundColorDark: '#FFFFFF',
    },
  },
  generalLayout: {
    headingFont: {
      mobile: {
        size: 20,
        weight: 400,
      },
      tablet: {
        size: 22,
        weight: 400,
      },
      desktop: {
        size: 24,
        weight: 400,
      },
    },
    bodyFont: {
      mobile: {
        size: 14,
        weight: 400,
      },
      tablet: {
        size: 14,
        weight: 400,
      },
      desktop: {
        size: 16,
        weight: 400,
      },
    },
    fontFamily: '',
    fontColor: '#000000',
    fontColorDark: '#FFFFFF',
    backgroundColor: '#FFFFFF',
    backgroundColorDark: '#000000',
    showWidgetTitle: true,
    showViSenzeLogo: false,
    darkModeDefault: false,
  },
};
