import type { WidgetConfig } from '../../common/wigmix-core';
import type { LanguagePack } from '../../common/locales/locale';

export const DEFAULT_TEXTS: LanguagePack = {
  en: {
    widgetTitle: 'Alternate Picks',
    searchBarInstructions: 'Or type your own recommendation query below',
    searchBarButton: 'Show Me',
    searchBarPlaceholder: 'an outfit to go with this',
    similarProducts: 'Similar Products',
    complementaryProducts: 'Complementary Products',
    systemError: 'Something went wrong. Please try again later.',
    imageOrQueryNotFound: 'The image or query was not found. Please try again later.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} off',
    addToCart: 'Add to Cart',
    a11ySearchBarInput: 'Type your recommendation query',
    a11yLoadingRecommendations: 'Loading recommendations',
    a11yProductResultsShown: 'Product results shown: {count}',
    a11yRecommendedProducts: 'Recommended products',
  },
  es: {
    widgetTitle: 'Personaliza tus recomendaciones',
    searchBarInstructions: 'O escribe tu propia consulta de recomendación a continuación',
    searchBarButton: 'Recomiéndame',
    searchBarPlaceholder: 'un conjunto para combinar con esto',
    similarProducts: 'Productos Similares',
    complementaryProducts: 'Productos Complementarios',
    systemError: 'Algo salió mal. Por favor, inténtelo más tarde.',
    imageOrQueryNotFound: 'La imagen o la consulta no se encontraron. Por favor, inténtelo más tarde.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de descuento',
    addToCart: 'Agregar al carrito',
    a11ySearchBarInput: 'Escribe tu consulta de recomendación',
    a11yLoadingRecommendations: 'Cargando recomendaciones',
    a11yProductResultsShown: 'Resultados de productos mostrados: {count}',
    a11yRecommendedProducts: 'Productos recomendados',
  },
  fr: {
    widgetTitle: 'Personnalisez vos recommandations',
    searchBarInstructions: 'Ou saisissez votre propre requête de recommandation ci-dessous',
    searchBarButton: 'Recommandez-moi',
    searchBarPlaceholder: 'une tenue pour aller avec ça',
    similarProducts: 'Produits Similaires',
    complementaryProducts: 'Produits Complémentaires',
    systemError: 'Une erreur est survenue. Veuillez réessayer plus tard.',
    imageOrQueryNotFound: 'L\'image ou la requête n\'a pas été trouvée. Veuillez réessayer plus tard.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de réduction',
    addToCart: 'Ajouter au panier',
    a11ySearchBarInput: 'Saisissez votre requête de recommandation',
    a11yLoadingRecommendations: 'Chargement des recommandations',
    a11yProductResultsShown: 'Résultats de produits affichés : {count}',
    a11yRecommendedProducts: 'Produits recommandés',
  },
  pt: {
    widgetTitle: 'Personalize suas recomendações',
    searchBarInstructions: 'Ou digite sua própria consulta de recomendação abaixo',
    searchBarButton: 'Recomende-me',
    searchBarPlaceholder: 'uma roupa para combinar com isto',
    similarProducts: 'Produtos Semelhantes',
    complementaryProducts: 'Produtos Complementares',
    systemError: 'Algo deu errado. Por favor, tente novamente mais tarde.',
    imageOrQueryNotFound: 'A imagem ou a consulta não foi encontrada. Por favor, tente novamente mais tarde.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} de desconto',
    addToCart: 'Adicionar ao carrinho',
    a11ySearchBarInput: 'Digite sua consulta de recomendação',
    a11yLoadingRecommendations: 'Carregando recomendações',
    a11yProductResultsShown: 'Resultados de produtos exibidos: {count}',
    a11yRecommendedProducts: 'Produtos recomendados',
  },
  de: {
    widgetTitle: 'Personalisiere deine Empfehlungen',
    searchBarInstructions: 'Oder geben Sie unten Ihre eigene Empfehlungssuche ein',
    searchBarButton: 'Empfiehl mir',
    searchBarPlaceholder: 'ein Outfit passend dazu',
    similarProducts: 'Ähnliche Produkte',
    complementaryProducts: 'Ergänzende Produkte',
    systemError: 'Etwas ist schief gelaufen. Bitte versuchen Sie es später erneut.',
    imageOrQueryNotFound: 'Die Bild oder die Abfrage wurde nicht gefunden. Bitte versuchen Sie es später erneut.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} Rabatt',
    addToCart: 'In den Warenkorb',
    a11ySearchBarInput: 'Geben Sie Ihre Empfehlungssuche ein',
    a11yLoadingRecommendations: 'Empfehlungen werden geladen',
    a11yProductResultsShown: 'Angezeigte Produktergebnisse: {count}',
    a11yRecommendedProducts: 'Empfohlene Produkte',
  },
  it: {
    widgetTitle: 'Personalizza i tuoi suggerimenti',
    searchBarInstructions: 'Oppure digita la tua query di raccomandazione qui sotto',
    searchBarButton: 'Consigliami',
    searchBarPlaceholder: 'un outfit da abbinare a questo',
    similarProducts: 'Prodotti Simili',
    complementaryProducts: 'Prodotti Complementari',
    systemError: 'Si è verificato un errore. Riprova più tardi.',
    imageOrQueryNotFound: 'L\'immagine o la query non sono state trovate. Riprova più tardi.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} di sconto',
    addToCart: 'Aggiungi al carrello',
    a11ySearchBarInput: 'Digita la tua query di raccomandazione',
    a11yLoadingRecommendations: 'Caricamento dei suggerimenti in corso',
    a11yProductResultsShown: 'Risultati prodotto mostrati: {count}',
    a11yRecommendedProducts: 'Prodotti consigliati',
  },
  pl: {
    widgetTitle: 'Spersonalizuj swoje rekomendacje',
    searchBarInstructions: 'Lub wpisz własne zapytanie dotyczące rekomendacji poniżej',
    searchBarButton: 'Zarekomenduj mi',
    searchBarPlaceholder: 'stylizacja pasująca do tego',
    similarProducts: 'Produkty Podobne',
    complementaryProducts: 'Produkty Uzupełniające',
    systemError: 'Wystąpił błąd. Spróbuj ponownie później.',
    imageOrQueryNotFound: 'Obraz lub zapytanie nie zostały znalezione. Spróbuj ponownie później.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} zniżki',
    addToCart: 'Dodaj do koszyka',
    a11ySearchBarInput: 'Wpisz zapytanie dotyczące rekomendacji',
    a11yLoadingRecommendations: 'Wczytywanie rekomendacji',
    a11yProductResultsShown: 'Wyświetlone wyniki produktów: {count}',
    a11yRecommendedProducts: 'Polecane produkty',
  },
  ko: {
    widgetTitle: '추천 맞춤 설정',
    searchBarInstructions: '또는 아래에 직접 추천 검색어를 입력하세요',
    searchBarButton: '추천해 주세요',
    searchBarPlaceholder: '이 상품에 어울리는 의상',
    similarProducts: '유사한 상품',
    complementaryProducts: '관련 상품',
    systemError: '오류가 발생했습니다. 나중에 다시 시도해주세요.',
    imageOrQueryNotFound: '이미지 또는 쿼리가 찾을 수 없습니다. 나중에 다시 시도해주세요.',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 할인',
    addToCart: '장바구니에 추가',
    a11ySearchBarInput: '추천 검색어를 입력하세요',
    a11yLoadingRecommendations: '추천 상품을 불러오는 중입니다',
    a11yProductResultsShown: '표시된 상품 결과: {count}',
    a11yRecommendedProducts: '추천 상품',
  },
  ja: {
    widgetTitle: 'おすすめをパーソナライズ',
    searchBarInstructions: 'または下に自分でおすすめの検索語を入力してください',
    searchBarButton: 'おすすめ',
    searchBarPlaceholder: 'これに合う服装',
    similarProducts: '類似商品',
    complementaryProducts: '関連商品',
    systemError: 'システムエラーが発生しました。後で再試してください。',
    imageOrQueryNotFound: '画像またはクエリが見つかりませんでした。後で再試してください。',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 割引',
    addToCart: 'カートに追加',
    a11ySearchBarInput: 'おすすめの検索語を入力してください',
    a11yLoadingRecommendations: 'おすすめを読み込んでいます',
    a11yProductResultsShown: '表示された商品件数: {count}',
    a11yRecommendedProducts: 'おすすめ商品',
  },
  th: {
    widgetTitle: 'ปรับแต่งคำแนะนำของคุณ',
    searchBarInstructions: 'หรือพิมพ์คำค้นหาที่คุณต้องการแนะนำด้านล่าง',
    searchBarButton: 'แนะนำฉัน',
    searchBarPlaceholder: 'ชุดที่จะเข้ากับสิ่งนี้',
    similarProducts: 'สินค้าที่คล้ายกัน',
    complementaryProducts: 'สินค้าเสริม',
    systemError: 'เกิดข้อผิดพลาด กรุณาลองอีกครั้ง',
    imageOrQueryNotFound: 'ไม่พบภาพหรือคำค้น กรุณาลองอีกครั้ง',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: 'ลดราคา {discount}',
    addToCart: 'เพิ่มสินค้าลงตะกร้า',
    a11ySearchBarInput: 'พิมพ์คำค้นหาที่คุณต้องการแนะนำ',
    a11yLoadingRecommendations: 'กำลังโหลดคำแนะนำ',
    a11yProductResultsShown: 'แสดงผลสินค้า {count} รายการ',
    a11yRecommendedProducts: 'สินค้าที่แนะนำ',
  },
  zh: {
    widgetTitle: '个性化推荐',
    searchBarInstructions: '描述您的需求，我们会为您查找合适的商品',
    searchBarButton: '为我推荐',
    searchBarPlaceholder: '搭配这件商品的造型',
    similarProducts: '相似商品',
    complementaryProducts: '搭配商品',
    systemError: '抱歉，系统暂时遇到问题，请稍后再试。',
    imageOrQueryNotFound: '您提供了无效的图片或查询，请移除后重试。',
    price: '{price}',
    originalPrice: '{originalPrice}',
    discount: '{discount} 折扣',
    addToCart: '加入购物车',
    a11ySearchBarInput: '请输入您的推荐搜索词',
    a11yLoadingRecommendations: '正在加载推荐商品',
    a11yProductResultsShown: '已显示商品结果：{count}',
    a11yRecommendedProducts: '推荐商品',
  },
};

export const DEFAULT_CUSTOMIZATIONS: WidgetConfig['customizations'] = {
  breakpoints: {
    mobile: {
      maxWidth: 767,
    },
    tablet: {
      maxWidth: 1023,
    },
  },
  productGrid: {
    mobile: {
      productsPerRow: 2,
      marginHorizontal: 16,
      marginVertical: 0,
    },
    tablet: {
      productsPerRow: 3,
      marginHorizontal: 8,
      marginVertical: 0,
    },
    desktop: {
      productsPerRow: 3,
      marginHorizontal: 8,
      marginVertical: 0,
    },
  },
  productCard: {
    imageAspectRatio: '2 / 3',
    openLinksInNewTab: false,
    price: {
      show: true,
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
      fontColor: '#EF4444',
      fontColorDark: '#EF4444',
    },
    originalPrice: {
      show: true,
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
      fontColor: '#9CA3AF',
      fontColorDark: '#9CA3AF',
      position: 'AFTER',
      strikethrough: true,
    },
    discount: {
      show: false,
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
      fontColor: '#EF4444',
      fontColorDark: '#EF4444',
      showPercentage: true,
      rounding: 1,
    },
    title: {
      show: false,
      fieldSource: 'title',
      font: {
        mobile: {
          size: 14,
          weight: 700,
        },
        tablet: {
          size: 14,
          weight: 700,
        },
        desktop: {
          size: 16,
          weight: 700,
        },
      },
    },
    secondaryTitle: {
      show: true,
      fieldSource: 'brand',
      font: {
        mobile: {
          size: 12,
          weight: 400,
        },
        tablet: {
          size: 12,
          weight: 400,
        },
        desktop: {
          size: 14,
          weight: 400,
        },
      },
    },
    images: {
      mainImage: 'main',
      hoverImage: 'additional',
      showAlternatives: false,
    },
    findSimilar: {
      enable: false,
      position: 'bottom_right',
      icon: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
    },
    addToWishlist: {
      enable: false,
      position: 'top_right',
      iconInactive: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
      iconActive: {
        color: '#000000',
        colorDark: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        backgroundColorDark: '#000000',
      },
    },
    addToCart: {
      enable: false,
      color: '#FFFFFF',
      colorDark: '#000000',
      backgroundColor: '#000000',
      backgroundColorDark: '#FFFFFF',
      layout: 'ICON_TEXT',
    },
  },
  buttons: {
    primary: {
      fontColor: '#FFFFFF',
      fontColorDark: '#616161',
      backgroundColor: '#616161',
      backgroundColorDark: '#FFFFFF',
    },
    secondary: {
      fontColor: '#FFFFFF',
      fontColorDark: '#000000',
      backgroundColor: '#000000',
      backgroundColorDark: '#FFFFFF',
    },
  },
  generalLayout: {
    headingFont: {
      mobile: {
        size: 20,
        weight: 400,
      },
      tablet: {
        size: 22,
        weight: 400,
      },
      desktop: {
        size: 24,
        weight: 400,
      },
    },
    bodyFont: {
      mobile: {
        size: 14,
        weight: 400,
      },
      tablet: {
        size: 14,
        weight: 400,
      },
      desktop: {
        size: 16,
        weight: 400,
      },
    },
    fontFamily: '',
    fontColor: '#000000',
    fontColorDark: '#FFFFFF',
    backgroundColor: '#FFFFFF',
    backgroundColorDark: '#000000',
    showWidgetTitle: true,
    showViSenzeLogo: false,
    darkModeDefault: false,
  },
};
