name: Pull Request and Build Checks

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Frontend Dependencies
        run: npm ci
      - name: Run Lint Checks
        run: npm run lint
  code_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Frontend Dependencies
        run: npm ci
      - name: Build Widgets
        run: npm run build
